#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np


STREAM3D_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = STREAM3D_ROOT.parent
AUDIT_ROOT = STREAM3D_ROOT / "outputs" / "audit"
PHASE_ID = "v104_lingbot_map_only_phase5_general_config_readiness"
DEFAULT_OUT = AUDIT_ROOT / PHASE_ID
GENERAL_DATASET_FILE = REPO_ROOT / "third_party/lingbot-map/benchmark/datasets/general.py"
LINGBOT_CHECKPOINT = REPO_ROOT / "third_party/lingbot-map/checkpoints/lingbot-map-long.pt"

IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".tiff", ".tif"}
SAMPLING_STRIDE = 5
SMOKE_START_IDX = 0


def _rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return p.resolve().relative_to(REPO_ROOT).as_posix()
    except Exception:
        return p.as_posix()


def _project(path: Path | str) -> Path:
    p = Path(path)
    if p.is_absolute():
        return p
    if p.parts and p.parts[0] == "Stream3D":
        return REPO_ROOT / p
    return STREAM3D_ROOT / p


def _jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return _rel(value)
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_jsonable(v) for v in value]
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    return value


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields or ["schema_version"])
        writer.writeheader()
        for row in rows:
            writer.writerow({key: _jsonable(row.get(key, "")) for key in fields})


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(_jsonable(payload), indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _image_count(path: Path) -> int:
    if not path.exists() or not path.is_dir():
        return 0
    return sum(1 for item in path.iterdir() if item.is_file() and item.suffix.lower() in IMAGE_EXTENSIONS)


def _candidate_roots(scene_id: str) -> list[Path]:
    return [
        REPO_ROOT / f"Stream3D/data/scannet/processed/{scene_id}/color",
        REPO_ROOT / f"Stream3D/data/scannet/processed/{scene_id}/rgb",
        REPO_ROOT / f"Stream3D/data/scannet/processed/{scene_id}/images",
        REPO_ROOT / f"data/scannet/processed/{scene_id}/color",
        REPO_ROOT / f"data/scannet/processed/{scene_id}/rgb",
        Path(f"/mnt/data/users/chengshun.wang/data/scannet/processed/{scene_id}/color"),
        Path(f"/mnt/data/users/chengshun.wang/data/scannet/processed/{scene_id}/rgb"),
    ]


def _prepare_symlink_rgb_root(out: Path, scene_id: str, source_root: Path | None) -> tuple[Path | None, int]:
    if source_root is None or not source_root.exists() or not source_root.is_dir():
        return None, 0
    prepared = out / "prepared_rgb_roots" / scene_id
    prepared.mkdir(parents=True, exist_ok=True)
    count = 0
    for image_path in sorted(source_root.iterdir()):
        if not image_path.is_file() or image_path.suffix.lower() not in IMAGE_EXTENSIONS:
            continue
        link_path = prepared / image_path.name
        if not link_path.exists():
            try:
                link_path.symlink_to(image_path.resolve())
            except FileExistsError:
                pass
        count += 1
    return prepared, count


def _write_template_config(out: Path, scene_id: str, rgb_root: Path | None, runnable: bool) -> dict[str, str]:
    config_dir = out / "configs" / scene_id
    dataset_name = f"stream4d_{scene_id}_general"
    method_name = "lingbot_map_stream4d_general"
    raw_root = str(rgb_root) if rgb_root is not None else f"TO_BE_FILLED_STREAM4D_RGB_DIR_{scene_id}"
    base_path = config_dir / "base_TEMPLATE.yaml"
    dataset_path = config_dir / "datasets" / f"{dataset_name}.yaml"
    method_path = config_dir / "methods" / f"{method_name}.yaml"
    workspace = out / "lingbot_workspace"
    base_text = "\n".join(
        [
            f"# Template generated by {PHASE_ID}.",
            "# This config is runnable only when raw_data_root points to a prepared per-scene RGB frame directory.",
            f"workspace: {workspace.as_posix()}",
            "",
            "evaluation:",
            "  traj:",
            "    enable: false",
            "    vis: false",
            "  auc:",
            "    enable: false",
            "  depth:",
            "    enable: false",
            "  points:",
            "    enable: false",
            "",
            "datasets:",
            f"  - {dataset_name}",
            "",
            "methods:",
            f"  - {method_name}",
            "",
        ]
    )
    dataset_text = "\n".join(
        [
            "dataset: general",
            f"raw_data_root: {raw_root}",
            "_load_img_size: 518",
            "_use_colmap: false",
            "sampling:",
            "  strategy: sequence",
            f"  stride: {SAMPLING_STRIDE}",
            "",
        ]
    )
    method_text = "\n".join(
        [
            "model: lingbot_map",
            "env: loger",
            f"_checkpoint: {LINGBOT_CHECKPOINT.as_posix()}",
            "_device: cuda",
            "_use_amp: true",
            "_use_sdpa: true",
            "_image_size: 518",
            "_patch_size: 14",
            "_enable_3d_rope: true",
            "_num_scale_frames: 8",
            "_max_frame_num: 1024",
            "_kv_cache_sliding_window: 64",
            "_kv_cache_scale_frames: 8",
            "_auto_keyframe_threshold: 320",
            "_area_budget: 255000",
            "_align: 14",
            "_mode: streaming",
            "_keyframe_interval: auto",
            "",
        ]
    )
    base_path.parent.mkdir(parents=True, exist_ok=True)
    dataset_path.parent.mkdir(parents=True, exist_ok=True)
    method_path.parent.mkdir(parents=True, exist_ok=True)
    base_path.write_text(base_text, encoding="utf-8")
    dataset_path.write_text(dataset_text, encoding="utf-8")
    method_path.write_text(method_text, encoding="utf-8")
    return {
        "base_config": _rel(base_path),
        "dataset_config": _rel(dataset_path),
        "method_config": _rel(method_path),
        "full_sampling_policy": f"sequence_stride{SAMPLING_STRIDE}",
        "full_stride_alignment": str(SAMPLING_STRIDE),
        "full_workspace_absolute": "True",
    }


def _write_smoke_config(out: Path, scene_id: str, rgb_root: Path | None, runnable: bool, num_frames: int) -> dict[str, str]:
    smoke_end_idx = SMOKE_START_IDX + int(num_frames) * SAMPLING_STRIDE
    smoke_frame_positions = list(range(SMOKE_START_IDX, smoke_end_idx, SAMPLING_STRIDE))
    config_dir = out / f"configs_smoke{num_frames}" / scene_id
    dataset_name = f"stream4d_{scene_id}_general_smoke{num_frames}"
    method_name = "lingbot_map_stream4d_general"
    raw_root = str(rgb_root) if rgb_root is not None else f"TO_BE_FILLED_STREAM4D_RGB_DIR_{scene_id}"
    base_path = config_dir / "base.yaml"
    dataset_path = config_dir / "datasets" / f"{dataset_name}.yaml"
    method_path = config_dir / "methods" / f"{method_name}.yaml"
    workspace = out / f"lingbot_workspace_smoke{num_frames}"
    base_text = "\n".join(
        [
            f"# Smoke config generated by {PHASE_ID}.",
            f"# Intended for schema/runtime validation only: first {num_frames} stride-{SAMPLING_STRIDE} frames.",
            f"workspace: {workspace.as_posix()}",
            "",
            "evaluation:",
            "  traj:",
            "    enable: false",
            "    vis: false",
            "  auc:",
            "    enable: false",
            "  depth:",
            "    enable: false",
            "  points:",
            "    enable: false",
            "",
            "datasets:",
            f"  - {dataset_name}",
            "",
            "methods:",
            f"  - {method_name}",
            "",
        ]
    )
    dataset_text = "\n".join(
        [
            "dataset: general",
            f"raw_data_root: {raw_root}",
            "_load_img_size: 518",
            "_use_colmap: false",
            "sampling:",
            "  strategy: sequence",
            f"  start_idx: {SMOKE_START_IDX}",
            f"  end_idx: {smoke_end_idx}",
            f"  stride: {SAMPLING_STRIDE}",
            "",
        ]
    )
    method_text = "\n".join(
        [
            "model: lingbot_map",
            "env: loger",
            f"_checkpoint: {LINGBOT_CHECKPOINT.as_posix()}",
            "_device: cuda",
            "_use_amp: true",
            "_use_sdpa: true",
            "_image_size: 518",
            "_patch_size: 14",
            "_enable_3d_rope: true",
            "_num_scale_frames: 8",
            "_max_frame_num: 1024",
            "_kv_cache_sliding_window: 64",
            "_kv_cache_scale_frames: 8",
            "_auto_keyframe_threshold: 320",
            "_area_budget: 255000",
            "_align: 14",
            "_mode: streaming",
            "_keyframe_interval: auto",
            "",
        ]
    )
    base_path.parent.mkdir(parents=True, exist_ok=True)
    dataset_path.parent.mkdir(parents=True, exist_ok=True)
    method_path.parent.mkdir(parents=True, exist_ok=True)
    base_path.write_text(base_text, encoding="utf-8")
    dataset_path.write_text(dataset_text, encoding="utf-8")
    method_path.write_text(method_text, encoding="utf-8")
    return {
        "smoke_base_config": _rel(base_path),
        "smoke_dataset_config": _rel(dataset_path),
        "smoke_method_config": _rel(method_path),
        "smoke_config_runnable_now": runnable,
        "smoke_sampling_policy": f"sequence_start{SMOKE_START_IDX}_end{smoke_end_idx}_stride{SAMPLING_STRIDE}",
        "smoke_stride_alignment": str(SAMPLING_STRIDE),
        "smoke_start_idx": str(SMOKE_START_IDX),
        "smoke_end_idx": str(smoke_end_idx),
        "smoke_frame_positions": ";".join(str(i) for i in smoke_frame_positions),
    }


def build(args: argparse.Namespace) -> dict[str, Any]:
    t0 = time.time()
    out = _project(args.output_root)
    if out.exists() and any(out.iterdir()) and not args.force:
        raise SystemExit(f"output root already exists and is non-empty; pass --force: {_rel(out)}")
    out.mkdir(parents=True, exist_ok=True)
    (out / "last_command.txt").write_text(" ".join([sys.executable, str(Path(__file__)), *sys.argv[1:]]) + "\n", encoding="utf-8")

    target_scenes = [part.strip() for part in str(args.target_scenes).split(",") if part.strip()]
    smoke_num_frames = int(args.smoke_num_frames)
    smoke_end_idx = SMOKE_START_IDX + smoke_num_frames * SAMPLING_STRIDE
    smoke_frame_positions = list(range(SMOKE_START_IDX, smoke_end_idx, SAMPLING_STRIDE))
    rgb_rows: list[dict[str, Any]] = []
    config_rows: list[dict[str, Any]] = []
    for scene_id in target_scenes:
        candidates = _candidate_roots(scene_id)
        candidate_counts = [(path, _image_count(path)) for path in candidates]
        best = next((path for path, count in candidate_counts if count > 0), None)
        for path, count in candidate_counts:
            rgb_rows.append(
                {
                    "schema_version": "stream4d_v104_lingbot_general_rgb_candidate_row_v1",
                    "phase_id": PHASE_ID,
                    "scene_id": scene_id,
                    "candidate_rgb_root": _rel(path),
                    "exists": path.exists(),
                    "is_dir": path.is_dir(),
                    "direct_image_count": count,
                    "selected_for_template": best is not None and path == best,
                }
            )
        prepared_root, prepared_count = _prepare_symlink_rgb_root(out, scene_id, best)
        runnable = prepared_root is not None and prepared_count > 0
        config_paths = _write_template_config(out, scene_id, prepared_root, runnable)
        smoke_paths = _write_smoke_config(out, scene_id, prepared_root, runnable, smoke_num_frames)
        config_rows.append(
            {
                "schema_version": "stream4d_v104_lingbot_general_template_row_v1",
                "phase_id": PHASE_ID,
                "scene_id": scene_id,
                "runnable_now": runnable,
                "selected_source_rgb_root": _rel(best) if best is not None else "",
                "prepared_rgb_root": _rel(prepared_root) if prepared_root is not None else "",
                "prepared_rgb_image_count": prepared_count,
                "blocker": "" if runnable else "MISSING_STREAM4D_RGB_FRAMES_FOR_LINGBOT_GENERAL_DATASET",
                **config_paths,
                **smoke_paths,
            }
        )

    adapter_available = GENERAL_DATASET_FILE.exists()
    checkpoint_available = LINGBOT_CHECKPOINT.exists()
    rgb_ready = bool(config_rows) and all(bool(row["runnable_now"]) for row in config_rows)
    readiness_pass = adapter_available and checkpoint_available and rgb_ready
    gate_rows = [
        {
            "schema_version": "stream4d_v104_lingbot_general_readiness_gate_row_v1",
            "phase_id": PHASE_ID,
            "gate_name": "lingbot_general_dataset_adapter_available",
            "pass": adapter_available,
            "observed": _rel(GENERAL_DATASET_FILE),
            "required": "general.py exists",
        },
        {
            "schema_version": "stream4d_v104_lingbot_general_readiness_gate_row_v1",
            "phase_id": PHASE_ID,
            "gate_name": "lingbot_checkpoint_available",
            "pass": checkpoint_available,
            "observed": _rel(LINGBOT_CHECKPOINT),
            "required": "lingbot-map-long.pt exists",
        },
        {
            "schema_version": "stream4d_v104_lingbot_general_readiness_gate_row_v1",
            "phase_id": PHASE_ID,
            "gate_name": "target_scene_rgb_frames_available",
            "pass": rgb_ready,
            "observed": {row["scene_id"]: row["prepared_rgb_root"] for row in config_rows},
            "required": "prepared per-scene RGB frame directory with images for every target scene",
        },
        {
            "schema_version": "stream4d_v104_lingbot_general_readiness_gate_row_v1",
            "phase_id": PHASE_ID,
            "gate_name": "lingbot_input_sampling_stride5_aligned",
            "pass": all(str(row.get("full_stride_alignment", "")) == str(SAMPLING_STRIDE) and str(row.get("smoke_stride_alignment", "")) == str(SAMPLING_STRIDE) for row in config_rows),
            "observed": {
                row["scene_id"]: {
                    "full_sampling_policy": row.get("full_sampling_policy", ""),
                    "smoke_sampling_policy": row.get("smoke_sampling_policy", ""),
                    "smoke_frame_positions": row.get("smoke_frame_positions", ""),
                }
                for row in config_rows
            },
            "required": "full and smoke LingBot inputs use sequence stride 5 aligned to DA3 frame grid",
        },
    ]
    summary = {
        "schema_version": "stream4d_v104_lingbot_general_config_readiness_summary_v1",
        "phase_id": PHASE_ID,
        "readiness_pass": readiness_pass,
        "taxonomy": "READY_TO_RUN_LINGBOT_GENERAL_CONFIGS" if readiness_pass else "BLOCKED_MISSING_STREAM4D_RGB_FRAMES_FOR_LINGBOT_GENERAL_DATASET",
        "blocker": "" if readiness_pass else "MISSING_STREAM4D_RGB_FRAMES_FOR_LINGBOT_GENERAL_DATASET",
        "target_scenes": target_scenes,
        "adapter_available": adapter_available,
        "checkpoint_available": checkpoint_available,
        "rgb_ready": rgb_ready,
        "template_configs_runnable_now": readiness_pass,
        "sampling_alignment": f"stride{SAMPLING_STRIDE}_da3_aligned",
        "sampling_contract_note": "Smoke configs intentionally omit num_frames because LingBot BaseDataset treats num_frames as uniform sampling; start/end/stride preserves the stride-5 grid.",
        "full_config_stride": SAMPLING_STRIDE,
        "smoke_num_frames": smoke_num_frames,
        "smoke_config_start_idx": SMOKE_START_IDX,
        "smoke_config_end_idx": smoke_end_idx,
        "smoke_config_stride": SAMPLING_STRIDE,
        "smoke_frame_positions": smoke_frame_positions,
        "prepared_rgb_roots": {row["scene_id"]: row["prepared_rgb_root"] for row in config_rows},
        "stream4d_metric_ready": False,
        "stream4d_metric_note": "Config readiness only; no LingBot run_worker/evaluate/report or AP/MV_AP metric is produced.",
        "outputs": {
            "rgb_candidate_rows": _rel(out / "rgb_candidate_rows.csv"),
            "config_template_rows": _rel(out / "config_template_rows.csv"),
            "gate_rows": _rel(out / "gate_rows.csv"),
            "summary": _rel(out / "summary.json"),
            "configs_dir": _rel(out / "configs"),
            "smoke_configs_dir": _rel(out / f"configs_smoke{int(args.smoke_num_frames)}"),
        },
        "runtime_sec": round(time.time() - t0, 3),
    }
    _write_csv(out / "rgb_candidate_rows.csv", rgb_rows)
    _write_csv(out / "config_template_rows.csv", config_rows)
    _write_csv(out / "gate_rows.csv", gate_rows)
    _write_json(out / "summary.json", summary)
    print(json.dumps(_jsonable(summary), indent=2, sort_keys=True))
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Check readiness for LingBot general-dataset configs on Stream4D target scenes.")
    parser.add_argument("--output-root", default=str(DEFAULT_OUT))
    parser.add_argument("--target-scenes", default="scene0011_00,scene0050_00")
    parser.add_argument("--smoke-num-frames", type=int, default=8)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    build(args)


if __name__ == "__main__":
    main()
