#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 GPU CANDIDATE_ID CHUNK_ID HORIZON" >&2
  exit 2
fi

GPU="$1"
CANDIDATE_ID="$2"
CHUNK_ID="$3"
HORIZON="$4"

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
V16_ROOT="${V16_ROOT:-results/kitti01_hmc_v2/acl2_v16_ttt_causalfork_candidatebank_target25}"
V18_ROOT="${V18_ROOT:-results/kitti01_hmc_v2/acl2_v18_ttt_write_true_actionspace_target25}"
PHASE1="$V16_ROOT/phase1_causalfork"
ROLLOUT_BASE="$V18_ROOT/rollouts"
MERGE_SAVE_BASE="$V18_ROOT/merge_state_snapshots"
TRACE_BASE="$V18_ROOT/true_action_traces"
SAVE_CANDIDATE_MERGE_STATES="${SAVE_CANDIDATE_MERGE_STATES:-0}"
SAVE_TRUE_ACTION_TRACE="${SAVE_TRUE_ACTION_TRACE:-0}"

case "$HORIZON" in
  3|5|8|10|15) ;;
  *) echo "Unsupported HORIZON: $HORIZON" >&2; exit 2 ;;
esac

case "$CHUNK_ID" in
  5) START_FRAME=145; SNAP="005"; BASE_GAMMA="0.005" ;;
  6) START_FRAME=174; SNAP="006"; BASE_GAMMA="0.005" ;;
  9) START_FRAME=261; SNAP="009"; BASE_GAMMA="0.005" ;;
  10) START_FRAME=290; SNAP="010"; BASE_GAMMA="0.003" ;;
  12) START_FRAME=348; SNAP="012"; BASE_GAMMA="0.003" ;;
  16) START_FRAME=464; SNAP="016"; BASE_GAMMA="0.0003" ;;
  *) echo "Unsupported CHUNK_ID: $CHUNK_ID" >&2; exit 2 ;;
esac

# Run one extra local chunk so the final evaluated overlap frames are merged
# with the same future context as the full causal run. Reports crop metrics
# back to the requested horizon window.
END_FRAME=$((START_FRAME + 32 + HORIZON * 29))

BASE_GAMMAS="5:0.005,6:0.005,7:0.005,8:0.005,9:0.005,10:0.003,11:0.003,12:0.003,16:0.0003"
BASE_TRI_PARAMS="5:0.35/0.12/0.85,6:0.35/0.12/0.85,7:0.35/0.12/0.85,8:0.35/0.12/0.85,9:0.35/0.12/0.85,10:0.35/0.12/0.85,11:0.35/0.12/0.85,12:0.35/0.12/0.85,16:0.35/0.08/0.85"
CHUNK_GAMMAS="$BASE_GAMMAS"

case "$CANDIDATE_ID" in
  K1_H9)
    ;;
  PZBASIS_01_CONTINUITY_BOOST_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=cosine_soft
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_MIN_COS=0.0
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.50
    export TTT_WRITE_NATIVE_MIX_SCALES=1.15,1.00,1.00
    ;;
  PZBASIS_02_HARM_SUPPRESS_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  PZBASIS_03_HARM_SUPPRESS_W0W2)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0,2
    ;;
  PZBASIS_04_SCALE_BASIS_SUPPRESS_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_COMMIT_FILTER_MODE=native_to_candidate_by_risk
    export TTT_WRITE_COMMIT_FILTER_RISK_SOURCE=ttt_update_conflict_energy
    export TTT_WRITE_COMMIT_FILTER_SCOPE=both_overlap
    export TTT_WRITE_COMMIT_FILTER_STAT=mean
    export TTT_WRITE_COMMIT_FILTER_BASE=0.0
    export TTT_WRITE_COMMIT_FILTER_GAIN=1.25
    export TTT_WRITE_COMMIT_FILTER_MIN=0.20
    export TTT_WRITE_COMMIT_FILTER_MAX=1.0
    export TTT_WRITE_COMMIT_FILTER_BRANCH_MASK=0
    ;;
  PZBASIS_05_OVERLAP_BASIS_BOOST_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_v
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.30
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.45
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  PZBASIS_06_CONTINUITY_PLUS_HARM_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.25
    export TTT_WRITE_NATIVE_MIX_SCALES=1.10,1.00,1.00
    ;;
  PZBASIS_07_LOWRANK_BASIS_RANK4)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=cap
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_CAP_RATIO=0.50
    ;;
  PZBASIS_08_LOWRANK_BASIS_RANK8)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=cap
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_CAP_RATIO=0.75
    ;;
  AUXGEO_TRUE_01_OVERLAP_POINTMAP_V_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_v
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_TRUE_02_OVERLAP_POINTMAP_KV_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_TRUE_03_OVERLAP_SCALE_PROXY_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_v
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.35
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.40
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_TRUE_04_OVERLAP_SCALE_PROXY_W0W2)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.35
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.40
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0,2
    ;;
  AUXGEO_TRUE_05_STRUCTURE_ONLY_OVERLAP_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    export TTT_WRITE_REPLAY_TOKEN_FILTER_MODE=overlap_static_topk
    export TTT_WRITE_REPLAY_TOKEN_FILTER_RATIO=0.60
    export TTT_WRITE_REPLAY_TOKEN_FILTER_SCOPE=both_overlap
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BRANCH_MASK=0
    ;;
  AUXGEO_TRUE_06_LOWD_STRUCTURE_OVERLAP_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    export TTT_WRITE_REPLAY_TOKEN_FILTER_MODE=overlap_static_topk
    export TTT_WRITE_REPLAY_TOKEN_FILTER_RATIO=0.35
    export TTT_WRITE_REPLAY_TOKEN_FILTER_SCOPE=both_overlap
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BRANCH_MASK=0
    ;;
  DLTRUE_01_SHORT_HARM_ONLY_W0)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.75
    export TTT_WRITE_TRANSIENT_DELTA_TTL=2
    ;;
  DLTRUE_02_SHORT_BODY_HARM_LONG_CONTINUITY)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.50
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.60
    export TTT_WRITE_TRANSIENT_DELTA_TTL=3
    export TTT_WRITE_NATIVE_MIX_SCALES=1.10,1.00,1.00
    ;;
  DLTRUE_03_SHORT_SCALE_CORRECTION_LONG_STRUCTURE)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0,2
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.65
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.50
    export TTT_WRITE_TRANSIENT_DELTA_TTL=2
    ;;
  DLTRUE_04_SHORT_OVERLAP_CORRECTION_LONG_NATIVE)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.35
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.75
    export TTT_WRITE_TRANSIENT_DELTA_TTL=3
    export TTT_WRITE_REPLAY_TOKEN_FILTER_MODE=overlap_static_topk
    export TTT_WRITE_REPLAY_TOKEN_FILTER_RATIO=0.50
    export TTT_WRITE_REPLAY_TOKEN_FILTER_SCOPE=both_overlap
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BRANCH_MASK=0
    ;;
  DLTRUE_05_SHORT_DECAY_FAST_K2)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.25
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.50
    export TTT_WRITE_TRANSIENT_DELTA_TTL=2
    ;;
  DLTRUE_06_SHORT_DECAY_SLOW_K5)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.25
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.50
    export TTT_WRITE_TRANSIENT_DELTA_TTL=5
    ;;
  DLTRUE_07_RESET_BOUND_SHORT_CLEAR)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.35
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.60
    export TTT_WRITE_TRANSIENT_DELTA_TTL=1
    ;;
  DLTRUE_08_EXIT_WEAK_SHORT_HANDOFF)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.50
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.35
    export TTT_WRITE_TRANSIENT_DELTA_TTL=3
    ;;
  *)
    echo "Unsupported CANDIDATE_ID for v18 true-action rollout: $CANDIDATE_ID" >&2
    exit 2
    ;;
esac

RUN_PREFIX="${RUN_PREFIX:-V18}"
RUN_NAME="${RUN_PREFIX}_${CANDIDATE_ID}_chunk${CHUNK_ID}_h${HORIZON}_globalgate_H9parent_SWKS3"
RUN_DIR="$ROOT/$ROLLOUT_BASE/$RUN_NAME"

SAVE_MERGE_ENV=()
if [ "$SAVE_CANDIDATE_MERGE_STATES" = "1" ]; then
  SAVE_MERGE_ENV=(
    SAVE_MERGE_STATES="$MERGE_SAVE_BASE/$RUN_NAME"
    SAVE_MERGE_STATE_KINDS=input,after
  )
fi

TRACE_ENV=()
if [ "$SAVE_TRUE_ACTION_TRACE" = "1" ]; then
  TRACE_ENV=(
    V11_PROJECTION_TRACE_DIR="$TRACE_BASE/$RUN_NAME"
  )
fi

if [ "${FORCE:-0}" != "1" ] && [ -f "$RUN_DIR/01.txt" ] && grep -q "DONE $RUN_NAME" "$RUN_DIR/run_status.txt" 2>/dev/null; then
  echo "SKIP existing DONE run: $RUN_NAME"
  exit 0
fi

env \
  KITTI_SEQ=01 \
  ATTN_CUE_BASE="$ROLLOUT_BASE" \
  START_FRAME="$START_FRAME" \
  END_FRAME="$END_FRAME" \
  GLOBAL_CHUNK_OFFSET="$CHUNK_ID" \
  RESET_EVERY=5 \
  WRITE_ALPHA=0.125 \
  READ_LAYER_MODE=all \
  READ_BETA_FRAME_CHUNKS="5:4.85,6:4.85,7:4.85,8:4.85,9:4.85,10:4.25,11:4.25,12:4.25,16:4.25" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.5 \
  SWA_OVERLAP_SOURCE_REPLACE_MODE=source \
  ENABLE_SWA_WRITE_CONTROL=1 \
  SWA_WRITE_LAYER_MODE=last \
  SWA_WRITE_KEEP_SCOPE=both_overlap \
  TTT_WRITE_GRADIENT_REVERSAL_MODE=tri_replay \
  TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE=update_conflict_energy \
  TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS="$CHUNK_GAMMAS" \
  TTT_WRITE_NATIVE_MIX_SCALES="${TTT_WRITE_NATIVE_MIX_SCALES:-1.10,1.00,1.00}" \
  TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC=0.35 \
  TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC=0.12 \
  TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA=0.85 \
  TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS="$BASE_TRI_PARAMS" \
  LOAD_HMC_STATE_AT_CHUNK="$PHASE1/state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_HMC_STATE_AT_CHUNK_INDEX=0 \
  LOAD_MERGE_STATE_AT_CHUNK="$PHASE1/merge_state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_MERGE_STATE_AT_CHUNK_INDEX=0 \
  "${SAVE_MERGE_ENV[@]}" \
  "${TRACE_ENV[@]}" \
  "$ROOT/tools/run_attention_cue_experiment.sh" \
  "$GPU" "$RUN_NAME" hybrid acl2.gg.qq.low.g2_3.past_only.headmean.robustq 4.75 stage_d_x_dg_inv_sqrt
