#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 3 ]; then
  echo "Usage: $0 GPU ROW RUN_NAME" >&2
  echo "Rows: AW010_ADAPTIVE_TTT_ONLY AW110_FRAME_ADAPTIVE_TTT AW111_FRAME_ADAPTIVE_TTT_SWA" >&2
  exit 2
fi

GPU="$1"
ROW="$2"
RUN_NAME="$3"

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
PY="${LOGER_PY:-/mnt/data/users/chengshun.wang/miniconda3/envs/loger/bin/python}"
RESULT_ROOT="${V47_RESULT_ROOT:-$ROOT/results/kitti01_hmc_v2/acl2_v47_adaptive_ttt_writer_nochunk}"
BASE="${V47_ROLLOUT_BASE:-$RESULT_ROOT/phase1_adaptive_writer/rollouts}"
OUT="$BASE/$RUN_NAME"
PLAN_NOTE="${V47_PLAN_NOTE:-$ROOT/docs/ACL2_v46B_ComponentAttribution_FrameTTT_FrameSWA_Addendum.md}"

mkdir -p "$OUT"
if [ -f "$OUT/run_status.txt" ] && grep -q "DONE $RUN_NAME" "$OUT/run_status.txt"; then
  echo "[v47] Skip completed run: $RUN_NAME"
  exit 0
fi

FRAME_ON=0
SWA_ON=0
case "$ROW" in
  AW010_ADAPTIVE_TTT_ONLY) ;;
  AW110_FRAME_ADAPTIVE_TTT) FRAME_ON=1 ;;
  AW111_FRAME_ADAPTIVE_TTT_SWA) FRAME_ON=1; SWA_ON=1 ;;
  *)
    echo "Unsupported v47 row: $ROW" >&2
    exit 2
    ;;
esac

# Hard no-chunk policy: this experiment is not allowed to inherit C9's
# KITTI01-specific chunk maps.
export ATTN_CUE_BASE="$BASE"
export LOGER_ROOT="$ROOT"
export LOGER_PY="$PY"
export KITTI_SEQ="${KITTI_SEQ:-01}"
export STAGE_C_MODE="${V47_STAGE_C_MODE:-none}"
export STAGE_C_CACHE_DIR="${V47_STAGE_C_CACHE_DIR:-${STAGE_C_CACHE_DIR:-}}"
export STAGE_C_CACHE_MODE="${V47_STAGE_C_CACHE_MODE:-off}"
export STAGE_C_CACHE_REQUIRE_HIT="${V47_STAGE_C_CACHE_REQUIRE_HIT:-0}"
export STAGE_C_CACHE_VALIDATE="${V47_STAGE_C_CACHE_VALIDATE:-0}"
export HMC_IGNORE_SEMANTIC_PRIOR="${V47_HMC_IGNORE_SEMANTIC_PRIOR:-${HMC_IGNORE_SEMANTIC_PRIOR:-0}}"
export EMPTY_CUDA_CACHE_EACH_CHUNK="${V47_EMPTY_CUDA_CACHE_EACH_CHUNK:-0}"
export SEMANTIC_ROLE_POLICY="${V47_SEMANTIC_ROLE_POLICY:-none}"
export SEMANTIC_MEMORY_PATHS="${V47_SEMANTIC_MEMORY_PATHS:-}"
export SEMANTIC_ROLE_HIGHD_QUANTILE="${V47_SEMANTIC_ROLE_HIGHD_QUANTILE:-${SEMANTIC_ROLE_HIGHD_QUANTILE:-0.80}}"
export SEMANTIC_ROLE_LOW_TRUST="${V47_SEMANTIC_ROLE_LOW_TRUST:-${SEMANTIC_ROLE_LOW_TRUST:-0.20}}"
export SEMANTIC_ROLE_POSITIVE_SCALE="${V47_SEMANTIC_ROLE_POSITIVE_SCALE:-${SEMANTIC_ROLE_POSITIVE_SCALE:-1.05}}"
export SEMANTIC_ROLE_NEUTRAL_SCALE="${V47_SEMANTIC_ROLE_NEUTRAL_SCALE:-${SEMANTIC_ROLE_NEUTRAL_SCALE:-0.85}}"
export SEMANTIC_ROLE_NEGATIVE_SCALE="${V47_SEMANTIC_ROLE_NEGATIVE_SCALE:-${SEMANTIC_ROLE_NEGATIVE_SCALE:-0.65}}"
export SEMANTIC_ROLE_SWA_NEGATIVE_SCALE="${V47_SEMANTIC_ROLE_SWA_NEGATIVE_SCALE:-${SEMANTIC_ROLE_SWA_NEGATIVE_SCALE:-1.0}}"
export SEMANTIC_ROLE_SWA_PROTECT_SCALE="${V47_SEMANTIC_ROLE_SWA_PROTECT_SCALE:-${SEMANTIC_ROLE_SWA_PROTECT_SCALE:-1.0}}"
export SEMANTIC_ROLE_CONTROL_MODE="${V47_SEMANTIC_ROLE_CONTROL_MODE:-${SEMANTIC_ROLE_CONTROL_MODE:-none}}"
export SEMANTIC_ROLE_CONTROL_SEED="${V47_SEMANTIC_ROLE_CONTROL_SEED:-${SEMANTIC_ROLE_CONTROL_SEED:-12345}}"
export SEMANTIC_ACTION_ACTIVE_CHUNKS=""
export READ_BETA_FRAME_CHUNKS=""
export TTT_WRITE_GRADIENT_REVERSAL_CHUNKS=""
export TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS=""
export TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS=""
export TTT_WRITE_COMMIT_EMA_CHUNKS=""
export TTT_WRITE_NATIVE_MIX_CHUNKS=""
export READ_TOPK_FRAC="${V47_READ_TOPK_FRAC:-0.0}"
export RHO_TTT_APPLY="${V47_RHO_TTT_APPLY:-${RHO_TTT_APPLY:-0.0}}"
export TTT_APPLY_MIN_GATE="${V47_TTT_APPLY_MIN_GATE:-${TTT_APPLY_MIN_GATE:-0.0}}"
export RESET_EVERY="${V47_RESET_EVERY:-5}"
export END_FRAME="${V47_END_FRAME:-10000}"

MODE="hybrid"
CUE="${V47_DG_CUE:-acl2.gg.qq.low.g2_3.past_only.headmean.robustq}"
BETA="${V47_READ_BETA:-4.75}"
WRITE_SCORE="${V47_TTT_WRITE_SCORE:-stage_d_x_dg_inv_sqrt}"

export READ_PATH="none"
export HMC_COMMIT_MODE="probe_ttt_write"
export TTT_WRITE_GRADIENT_REVERSAL_MODE="tri_replay"
export TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE="${V47_TTT_RISK_SOURCE:-update_conflict_energy}"
export TTT_WRITE_GRADIENT_REVERSAL_BRANCH_MASK="${V47_TTT_BRANCH_MASK:-0}"
export TTT_WRITE_GRADIENT_REVERSAL_BRANCH_GAMMAS="${V47_TTT_BRANCH_GAMMAS:-}"
export TTT_WRITE_GRADIENT_REVERSAL_LAYER_GAMMAS="${V47_TTT_LAYER_GAMMAS:-}"
export TTT_WRITE_GRADIENT_REVERSAL_HEAD_ROUTES="${V47_TTT_HEAD_ROUTES:-}"

# Adaptive writer contract:
# - external gamma is zero;
# - manual tri-replay positive/negative/neutral percentages are zero and unused;
# - role assignment and negative write magnitude are inferred from the online
#   risk distribution inside ttt_write_controller.py.
export TTT_WRITE_GRADIENT_REVERSAL_GAMMA="0.0"
export TTT_WRITE_GRADIENT_REVERSAL_NEGATIVE_FRAC="0.0"
export TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC="0.0"
export TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC="0.0"
export TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA="0.0"
export TTT_WRITE_TRI_REPLAY_ROLE_MODE="${V47_TTT_ROLE_MODE:-adaptive_writer_fused}"
if [[ "$TTT_WRITE_TRI_REPLAY_ROLE_MODE" == *split* ]]; then
  ADAPTIVE_WRITER_DEFINITION="online risk/prior adaptive role assignment + adaptive negative gamma/lambda + split tri replay"
else
  ADAPTIVE_WRITER_DEFINITION="online risk/prior adaptive role assignment + adaptive negative gamma/lambda + fused single replay"
fi

export TTT_WRITE_COMMIT_EMA_ALPHA="1.0"
export TTT_WRITE_COMMIT_EMA_BRANCH_MASK="all"
export TTT_WRITE_NATIVE_MIX_SCALES="${V47_NATIVE_MIX_SCALES:-1.00,1.00,1.00}"
export TTT_WRITE_NATIVE_MIX_CHUNKS=""
export TTT_WRITE_COMMIT_FILTER_MODE="${V47_TTT_COMMIT_FILTER_MODE:-none}"
export TTT_WRITE_COMMIT_FILTER_RISK_SOURCE="${V47_TTT_COMMIT_FILTER_RISK_SOURCE:-d_tok}"
export TTT_WRITE_COMMIT_FILTER_SCOPE="${V47_TTT_COMMIT_FILTER_SCOPE:-tail_overlap}"
export TTT_WRITE_COMMIT_FILTER_STAT="${V47_TTT_COMMIT_FILTER_STAT:-mean}"
export TTT_WRITE_COMMIT_FILTER_BASE="${V47_TTT_COMMIT_FILTER_BASE:-0.0}"
export TTT_WRITE_COMMIT_FILTER_GAIN="${V47_TTT_COMMIT_FILTER_GAIN:-1.0}"
export TTT_WRITE_COMMIT_FILTER_MIN="${V47_TTT_COMMIT_FILTER_MIN:-0.0}"
export TTT_WRITE_COMMIT_FILTER_MAX="${V47_TTT_COMMIT_FILTER_MAX:-1.0}"
export TTT_WRITE_COMMIT_FILTER_BRANCH_MASK="${V47_TTT_COMMIT_FILTER_BRANCH_MASK:-0}"
export TTT_WRITE_COMMIT_FILTER_CHUNKS=""
export TTT_WRITE_SCALE_STATE_MODE="${V47_TTT_SCALE_STATE_MODE:-none}"
export TTT_WRITE_SCALE_STATE_PROXY="${V47_TTT_SCALE_STATE_PROXY:-pose_step_ema}"
export TTT_WRITE_SCALE_STATE_CARRIER="${V47_TTT_SCALE_STATE_CARRIER:-all}"
export TTT_WRITE_SCALE_STATE_ALPHA="${V47_TTT_SCALE_STATE_ALPHA:-0.0}"
export TTT_WRITE_SCALE_STATE_BRANCH_MASK="${V47_TTT_SCALE_STATE_BRANCH_MASK:-0}"
export TTT_WRITE_SCALE_STATE_CHUNKS=""
export TTT_WRITE_SCALE_STATE_SAMPLE_TOKENS="${V47_TTT_SCALE_STATE_SAMPLE_TOKENS:-0}"
export ONLINE_SCALE_STATE_MODE="${V47_ONLINE_SCALE_STATE_MODE:-none}"
export ONLINE_SCALE_STATE_MIN="${V47_ONLINE_SCALE_STATE_MIN:-0.80}"
export ONLINE_SCALE_STATE_MAX="${V47_ONLINE_SCALE_STATE_MAX:-1.25}"

export ENABLE_SWA_WRITE_CONTROL="${V47_ENABLE_SWA_WRITE_CONTROL:-${ENABLE_SWA_WRITE_CONTROL:-0}}"
export SWA_WRITE_MODE="${V47_SWA_WRITE_MODE:-${SWA_WRITE_MODE:-none}}"
export SWA_WRITE_RHO="${V47_SWA_WRITE_RHO:-${SWA_WRITE_RHO:-0.0}}"
export SWA_WRITE_MIN_GATE="${V47_SWA_WRITE_MIN_GATE:-${SWA_WRITE_MIN_GATE:-0.0}}"
export SWA_WRITE_SPARSE_RATIO="${V47_SWA_WRITE_SPARSE_RATIO:-${SWA_WRITE_SPARSE_RATIO:-1.0}}"
export SWA_WRITE_LAYER_MODE="${V47_SWA_WRITE_LAYER_MODE:-${SWA_WRITE_LAYER_MODE:-all}}"
export SWA_WRITE_SINGLE_LAYER="${V47_SWA_WRITE_SINGLE_LAYER:-${SWA_WRITE_SINGLE_LAYER:-}}"
export SWA_WRITE_SCOPE="${V47_SWA_WRITE_SCOPE:-${SWA_WRITE_SCOPE:-all}}"
export SWA_WRITE_KEEP_SCOPE="${V47_SWA_WRITE_KEEP_SCOPE:-${SWA_WRITE_KEEP_SCOPE:-all}}"
export SWA_WRITE_SCORE_SOURCE="${V47_SWA_WRITE_SCORE_SOURCE:-${SWA_WRITE_SCORE_SOURCE:-read}}"
export SWA_WRITE_CACHE_BLEND_ALPHA="${V47_SWA_WRITE_CACHE_BLEND_ALPHA:-${SWA_WRITE_CACHE_BLEND_ALPHA:-0.0}}"
export SWA_WRITE_CACHE_BLEND_MODE="${V47_SWA_WRITE_CACHE_BLEND_MODE:-${SWA_WRITE_CACHE_BLEND_MODE:-dynamic}}"
export SWA_WRITE_CACHE_BLEND_TARGET="${V47_SWA_WRITE_CACHE_BLEND_TARGET:-${SWA_WRITE_CACHE_BLEND_TARGET:-v}}"
export ENABLE_SWA_OVERLAP_SOURCE_GATE="${V47_ENABLE_SWA_OVERLAP_SOURCE_GATE:-${ENABLE_SWA_OVERLAP_SOURCE_GATE:-0}}"
export SWA_OVERLAP_SOURCE_GATE_RHO="${V47_SWA_OVERLAP_SOURCE_GATE_RHO:-${SWA_OVERLAP_SOURCE_GATE_RHO:-0.0}}"
export SWA_OVERLAP_SOURCE_GATE_MIN="${V47_SWA_OVERLAP_SOURCE_GATE_MIN:-${SWA_OVERLAP_SOURCE_GATE_MIN:-0.85}}"
export SWA_OVERLAP_SOURCE_GATE_MODE="${V47_SWA_OVERLAP_SOURCE_GATE_MODE:-${SWA_OVERLAP_SOURCE_GATE_MODE:-source}}"
export SWA_OVERLAP_SOURCE_GATE_TARGET="${V47_SWA_OVERLAP_SOURCE_GATE_TARGET:-${SWA_OVERLAP_SOURCE_GATE_TARGET:-v}}"
export SWA_OVERLAP_SOURCE_GATE_LAYER_MODE="${V47_SWA_OVERLAP_SOURCE_GATE_LAYER_MODE:-${SWA_OVERLAP_SOURCE_GATE_LAYER_MODE:-last}}"
export SWA_OVERLAP_SOURCE_GATE_SINGLE_LAYER="${V47_SWA_OVERLAP_SOURCE_GATE_SINGLE_LAYER:-${SWA_OVERLAP_SOURCE_GATE_SINGLE_LAYER:-}}"
export ENABLE_SWA_OVERLAP_SOURCE_REPLACE="${V47_ENABLE_SWA_OVERLAP_SOURCE_REPLACE:-${ENABLE_SWA_OVERLAP_SOURCE_REPLACE:-0}}"
export SWA_OVERLAP_SOURCE_REPLACE_ALPHA="${V47_SWA_OVERLAP_SOURCE_REPLACE_ALPHA:-${V47_SWA_ALPHA:-${SWA_OVERLAP_SOURCE_REPLACE_ALPHA:-0.0}}}"
export SWA_OVERLAP_SOURCE_REPLACE_MODE="${V47_SWA_OVERLAP_SOURCE_REPLACE_MODE:-${V47_SWA_REPLACE_MODE:-${SWA_OVERLAP_SOURCE_REPLACE_MODE:-source}}}"
export SWA_OVERLAP_SOURCE_REPLACE_TARGET="${V47_SWA_OVERLAP_SOURCE_REPLACE_TARGET:-${V47_SWA_REPLACE_TARGET:-${SWA_OVERLAP_SOURCE_REPLACE_TARGET:-kv}}}"
export SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE="${V47_SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE:-${V47_SWA_REPLACE_LAYER_MODE:-${SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE:-last}}}"
export SWA_OVERLAP_SOURCE_REPLACE_SINGLE_LAYER="${V47_SWA_OVERLAP_SOURCE_REPLACE_SINGLE_LAYER:-${SWA_OVERLAP_SOURCE_REPLACE_SINGLE_LAYER:-}}"
export READ_LAYER_MODE="${V47_READ_LAYER_MODE:-early}"
export READ_SINGLE_LAYER="${V47_READ_SINGLE_LAYER:--1}"
READ_PATH_OVERRIDE="${V47_READ_PATH_OVERRIDE:-}"

if [ "$FRAME_ON" -eq 1 ]; then
  export READ_PATH="frame"
  export FRAME_BIAS_MODE="${V47_FRAME_BIAS_MODE:-pair}"
fi

if [ -n "$READ_PATH_OVERRIDE" ]; then
  export READ_PATH="$READ_PATH_OVERRIDE"
fi

if [ "$SWA_ON" -eq 1 ]; then
  if [ -z "${V47_ENABLE_SWA_OVERLAP_SOURCE_REPLACE+x}" ]; then
    export ENABLE_SWA_OVERLAP_SOURCE_REPLACE="1"
  fi
  if [ -z "${V47_SWA_OVERLAP_SOURCE_REPLACE_ALPHA+x}" ] && [ -z "${V47_SWA_ALPHA+x}" ]; then
    export SWA_OVERLAP_SOURCE_REPLACE_ALPHA="0.5"
  fi
fi

cat > "$OUT/effective_config.yaml" <<EOF
row: "$ROW"
run_name: "$RUN_NAME"
plan_note: "$PLAN_NOTE"
frame_attn_expected: $FRAME_ON
adaptive_ttt_expected: 1
swa_expected: $SWA_ON
mode: "$MODE"
cue: "$CUE"
beta: "$BETA"
write_score: "$WRITE_SCORE"
read_path: "$READ_PATH"
read_path_override: "$READ_PATH_OVERRIDE"
read_layer_mode: "$READ_LAYER_MODE"
read_single_layer: "$READ_SINGLE_LAYER"
rho_ttt_apply: "$RHO_TTT_APPLY"
ttt_apply_min_gate: "$TTT_APPLY_MIN_GATE"
hmc_commit_mode: "$HMC_COMMIT_MODE"
read_beta_frame_chunks: "$READ_BETA_FRAME_CHUNKS"
ttt_write_gradient_reversal_mode: "$TTT_WRITE_GRADIENT_REVERSAL_MODE"
ttt_write_gradient_reversal_gamma: "$TTT_WRITE_GRADIENT_REVERSAL_GAMMA"
ttt_write_gradient_reversal_risk_source: "$TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE"
ttt_write_gradient_reversal_branch_mask: "$TTT_WRITE_GRADIENT_REVERSAL_BRANCH_MASK"
ttt_write_gradient_reversal_branch_gammas: "$TTT_WRITE_GRADIENT_REVERSAL_BRANCH_GAMMAS"
ttt_write_gradient_reversal_layer_gammas: "$TTT_WRITE_GRADIENT_REVERSAL_LAYER_GAMMAS"
ttt_write_gradient_reversal_head_routes: "$TTT_WRITE_GRADIENT_REVERSAL_HEAD_ROUTES"
ttt_write_gradient_reversal_chunk_gammas: "$TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS"
ttt_write_tri_replay_positive_frac: "$TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC"
ttt_write_tri_replay_negative_frac: "$TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC"
ttt_write_tri_replay_neutral_lambda: "$TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA"
ttt_write_tri_replay_role_mode: "$TTT_WRITE_TRI_REPLAY_ROLE_MODE"
ttt_write_tri_replay_chunk_params: "$TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS"
ttt_write_commit_ema_alpha: "$TTT_WRITE_COMMIT_EMA_ALPHA"
ttt_write_commit_ema_branch_mask: "$TTT_WRITE_COMMIT_EMA_BRANCH_MASK"
ttt_write_commit_ema_chunks: "$TTT_WRITE_COMMIT_EMA_CHUNKS"
ttt_write_native_mix_scales: "$TTT_WRITE_NATIVE_MIX_SCALES"
ttt_write_native_mix_chunks: "$TTT_WRITE_NATIVE_MIX_CHUNKS"
ttt_write_commit_filter_mode: "$TTT_WRITE_COMMIT_FILTER_MODE"
ttt_write_commit_filter_risk_source: "$TTT_WRITE_COMMIT_FILTER_RISK_SOURCE"
ttt_write_commit_filter_scope: "$TTT_WRITE_COMMIT_FILTER_SCOPE"
ttt_write_commit_filter_stat: "$TTT_WRITE_COMMIT_FILTER_STAT"
ttt_write_commit_filter_base: "$TTT_WRITE_COMMIT_FILTER_BASE"
ttt_write_commit_filter_gain: "$TTT_WRITE_COMMIT_FILTER_GAIN"
ttt_write_commit_filter_min: "$TTT_WRITE_COMMIT_FILTER_MIN"
ttt_write_commit_filter_max: "$TTT_WRITE_COMMIT_FILTER_MAX"
ttt_write_commit_filter_branch_mask: "$TTT_WRITE_COMMIT_FILTER_BRANCH_MASK"
ttt_write_commit_filter_chunks: "$TTT_WRITE_COMMIT_FILTER_CHUNKS"
ttt_write_scale_state_mode: "$TTT_WRITE_SCALE_STATE_MODE"
ttt_write_scale_state_proxy: "$TTT_WRITE_SCALE_STATE_PROXY"
ttt_write_scale_state_carrier: "$TTT_WRITE_SCALE_STATE_CARRIER"
ttt_write_scale_state_alpha: "$TTT_WRITE_SCALE_STATE_ALPHA"
ttt_write_scale_state_branch_mask: "$TTT_WRITE_SCALE_STATE_BRANCH_MASK"
ttt_write_scale_state_chunks: "$TTT_WRITE_SCALE_STATE_CHUNKS"
ttt_write_scale_state_sample_tokens: "$TTT_WRITE_SCALE_STATE_SAMPLE_TOKENS"
online_scale_state_mode: "$ONLINE_SCALE_STATE_MODE"
online_scale_state_min: "$ONLINE_SCALE_STATE_MIN"
online_scale_state_max: "$ONLINE_SCALE_STATE_MAX"
enable_swa_write_control: "$ENABLE_SWA_WRITE_CONTROL"
swa_write_mode: "$SWA_WRITE_MODE"
swa_write_rho: "$SWA_WRITE_RHO"
swa_write_min_gate: "$SWA_WRITE_MIN_GATE"
swa_write_sparse_ratio: "$SWA_WRITE_SPARSE_RATIO"
swa_write_layer_mode: "$SWA_WRITE_LAYER_MODE"
swa_write_single_layer: "$SWA_WRITE_SINGLE_LAYER"
swa_write_scope: "$SWA_WRITE_SCOPE"
swa_write_keep_scope: "$SWA_WRITE_KEEP_SCOPE"
swa_write_score_source: "$SWA_WRITE_SCORE_SOURCE"
swa_write_cache_blend_alpha: "$SWA_WRITE_CACHE_BLEND_ALPHA"
swa_write_cache_blend_mode: "$SWA_WRITE_CACHE_BLEND_MODE"
swa_write_cache_blend_target: "$SWA_WRITE_CACHE_BLEND_TARGET"
enable_swa_overlap_source_gate: "$ENABLE_SWA_OVERLAP_SOURCE_GATE"
swa_overlap_source_gate_rho: "$SWA_OVERLAP_SOURCE_GATE_RHO"
swa_overlap_source_gate_min: "$SWA_OVERLAP_SOURCE_GATE_MIN"
swa_overlap_source_gate_mode: "$SWA_OVERLAP_SOURCE_GATE_MODE"
swa_overlap_source_gate_target: "$SWA_OVERLAP_SOURCE_GATE_TARGET"
swa_overlap_source_gate_layer_mode: "$SWA_OVERLAP_SOURCE_GATE_LAYER_MODE"
swa_overlap_source_gate_single_layer: "$SWA_OVERLAP_SOURCE_GATE_SINGLE_LAYER"
enable_swa_overlap_source_replace: "$ENABLE_SWA_OVERLAP_SOURCE_REPLACE"
swa_overlap_source_replace_alpha: "$SWA_OVERLAP_SOURCE_REPLACE_ALPHA"
swa_overlap_source_replace_mode: "$SWA_OVERLAP_SOURCE_REPLACE_MODE"
swa_overlap_source_replace_target: "$SWA_OVERLAP_SOURCE_REPLACE_TARGET"
swa_overlap_source_replace_layer_mode: "$SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE"
swa_overlap_source_replace_single_layer: "$SWA_OVERLAP_SOURCE_REPLACE_SINGLE_LAYER"
stage_c_mode: "$STAGE_C_MODE"
stage_c_cache_dir: "$STAGE_C_CACHE_DIR"
stage_c_cache_mode: "$STAGE_C_CACHE_MODE"
stage_c_cache_require_hit: "$STAGE_C_CACHE_REQUIRE_HIT"
stage_c_cache_validate: "$STAGE_C_CACHE_VALIDATE"
hmc_ignore_semantic_prior: "$HMC_IGNORE_SEMANTIC_PRIOR"
empty_cuda_cache_each_chunk: "$EMPTY_CUDA_CACHE_EACH_CHUNK"
semantic_role_policy: "$SEMANTIC_ROLE_POLICY"
semantic_memory_paths: "$SEMANTIC_MEMORY_PATHS"
semantic_role_highd_quantile: "$SEMANTIC_ROLE_HIGHD_QUANTILE"
semantic_role_low_trust: "$SEMANTIC_ROLE_LOW_TRUST"
semantic_role_positive_scale: "$SEMANTIC_ROLE_POSITIVE_SCALE"
semantic_role_neutral_scale: "$SEMANTIC_ROLE_NEUTRAL_SCALE"
semantic_role_negative_scale: "$SEMANTIC_ROLE_NEGATIVE_SCALE"
semantic_role_swa_negative_scale: "$SEMANTIC_ROLE_SWA_NEGATIVE_SCALE"
semantic_role_swa_protect_scale: "$SEMANTIC_ROLE_SWA_PROTECT_SCALE"
semantic_role_control_mode: "$SEMANTIC_ROLE_CONTROL_MODE"
semantic_role_control_seed: "$SEMANTIC_ROLE_CONTROL_SEED"
semantic_action_active_chunks: "$SEMANTIC_ACTION_ACTIVE_CHUNKS"
enable_context_source_skip: "${ENABLE_CONTEXT_SOURCE_SKIP:-0}"
context_source_skip_impl: "${CONTEXT_SOURCE_SKIP_IMPL:-bias}"
context_source_skip_scope: "${CONTEXT_SOURCE_SKIP_SCOPE:-frame}"
context_source_skip_mode: "${CONTEXT_SOURCE_SKIP_MODE:-hard}"
context_source_skip_mask: "${CONTEXT_SOURCE_SKIP_MASK:-dg_q90}"
context_source_skip_layer_mode: "${CONTEXT_SOURCE_SKIP_LAYER_MODE:-early}"
context_source_skip_single_layer: "${CONTEXT_SOURCE_SKIP_SINGLE_LAYER:-}"
context_source_skip_soft_rho: "${CONTEXT_SOURCE_SKIP_SOFT_RHO:-0.5}"
context_source_skip_soft_min_keep: "${CONTEXT_SOURCE_SKIP_SOFT_MIN_KEEP:-0.5}"
context_source_skip_record_attention_mass: "${CONTEXT_SOURCE_SKIP_RECORD_ATTENTION_MASS:-0}"
EOF
cp "$OUT/effective_config.yaml" "$OUT/v47_effective_config.yaml"

cat > "$OUT/adaptive_writer_audit.json" <<EOF
{
  "row": "$ROW",
  "run_name": "$RUN_NAME",
  "adaptive_ttt_writer": true,
  "no_chunk_id_policy": true,
  "no_manual_tri_replay_percentages": true,
  "manual_tri_replay_positive_frac": "$TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC",
  "manual_tri_replay_negative_frac": "$TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC",
  "manual_tri_replay_neutral_lambda": "$TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA",
  "external_gamma": "$TTT_WRITE_GRADIENT_REVERSAL_GAMMA",
  "role_mode": "$TTT_WRITE_TRI_REPLAY_ROLE_MODE",
  "definition": "$ADAPTIVE_WRITER_DEFINITION"
}
EOF
cat > "$OUT/adaptive_ttt_audit.json" <<EOF
{
  "row": "$ROW",
  "run_name": "$RUN_NAME",
  "adaptive_ttt_writer": true,
  "no_chunk_id_policy": true,
  "manual_positive_frac": 0.0,
  "manual_negative_frac": 0.0,
  "manual_neutral_lambda": 0.0,
  "no_manual_tri_replay_percentages": true,
  "external_gamma": 0.0,
  "role_mode": "$TTT_WRITE_TRI_REPLAY_ROLE_MODE",
  "commit_filter_mode": "$TTT_WRITE_COMMIT_FILTER_MODE",
  "risk_source": "$TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE",
  "scale_state_mode": "$TTT_WRITE_SCALE_STATE_MODE",
  "scale_state_chunks_empty": true,
  "scale_state_sample_tokens": "$TTT_WRITE_SCALE_STATE_SAMPLE_TOKENS",
  "native_mix_scales": "$TTT_WRITE_NATIVE_MIX_SCALES",
  "split_required": true,
  "definition": "$ADAPTIVE_WRITER_DEFINITION"
}
EOF

cat > "$OUT/chunk_id_policy_audit.json" <<EOF
{
  "has_read_beta_frame_chunks": false,
  "has_tri_gamma_chunk_map": false,
  "has_tri_replay_chunk_params": false,
  "has_commit_ema_chunks": false,
  "has_native_mix_chunks": false,
  "has_semantic_action_active_chunks": false,
  "read_beta_frame_chunks_empty": true,
  "ttt_gradient_reversal_chunk_gammas_empty": true,
  "ttt_tri_replay_chunk_params_empty": true,
  "ttt_commit_ema_chunks_empty": true,
  "native_mix_chunks_empty": true,
  "semantic_action_active_chunks_empty": true,
  "scale_state_chunks_empty": true,
  "read_beta_frame_chunks": "$READ_BETA_FRAME_CHUNKS",
  "tri_gamma_chunk_map": "$TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS",
  "tri_replay_chunk_params": "$TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS",
  "commit_ema_chunks": "$TTT_WRITE_COMMIT_EMA_CHUNKS",
  "native_mix_chunks": "$TTT_WRITE_NATIVE_MIX_CHUNKS",
  "scale_state_chunks": "$TTT_WRITE_SCALE_STATE_CHUNKS",
  "scale_state_sample_tokens": "$TTT_WRITE_SCALE_STATE_SAMPLE_TOKENS",
  "semantic_action_active_chunks": ""
}
EOF

cat > "$OUT/reproduce_command.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
cd "$ROOT"
V47_RESULT_ROOT="$RESULT_ROOT" \\
V47_ROLLOUT_BASE="$BASE" \\
V47_PLAN_NOTE="$PLAN_NOTE" \\
V47_END_FRAME="$END_FRAME" \\
V47_RESET_EVERY="$RESET_EVERY" \\
V47_DG_CUE="$CUE" \\
V47_READ_BETA="$BETA" \\
V47_READ_PATH_OVERRIDE="$READ_PATH_OVERRIDE" \\
V47_READ_LAYER_MODE="$READ_LAYER_MODE" \\
V47_READ_SINGLE_LAYER="$READ_SINGLE_LAYER" \\
V47_READ_TOPK_FRAC="$READ_TOPK_FRAC" \\
V47_RHO_TTT_APPLY="$RHO_TTT_APPLY" \\
V47_TTT_APPLY_MIN_GATE="$TTT_APPLY_MIN_GATE" \\
V47_TTT_WRITE_SCORE="$WRITE_SCORE" \\
V47_TTT_RISK_SOURCE="$TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE" \\
V47_TTT_ROLE_MODE="$TTT_WRITE_TRI_REPLAY_ROLE_MODE" \\
V47_TTT_BRANCH_MASK="$TTT_WRITE_GRADIENT_REVERSAL_BRANCH_MASK" \\
V47_TTT_BRANCH_GAMMAS="$TTT_WRITE_GRADIENT_REVERSAL_BRANCH_GAMMAS" \\
V47_TTT_LAYER_GAMMAS="$TTT_WRITE_GRADIENT_REVERSAL_LAYER_GAMMAS" \\
V47_TTT_HEAD_ROUTES="$TTT_WRITE_GRADIENT_REVERSAL_HEAD_ROUTES" \\
V47_NATIVE_MIX_SCALES="$TTT_WRITE_NATIVE_MIX_SCALES" \\
V47_TTT_COMMIT_FILTER_MODE="$TTT_WRITE_COMMIT_FILTER_MODE" \\
V47_TTT_COMMIT_FILTER_RISK_SOURCE="$TTT_WRITE_COMMIT_FILTER_RISK_SOURCE" \\
V47_TTT_COMMIT_FILTER_SCOPE="$TTT_WRITE_COMMIT_FILTER_SCOPE" \\
V47_TTT_COMMIT_FILTER_STAT="$TTT_WRITE_COMMIT_FILTER_STAT" \\
V47_TTT_COMMIT_FILTER_BASE="$TTT_WRITE_COMMIT_FILTER_BASE" \\
V47_TTT_COMMIT_FILTER_GAIN="$TTT_WRITE_COMMIT_FILTER_GAIN" \\
V47_TTT_COMMIT_FILTER_MIN="$TTT_WRITE_COMMIT_FILTER_MIN" \\
V47_TTT_COMMIT_FILTER_MAX="$TTT_WRITE_COMMIT_FILTER_MAX" \\
V47_TTT_COMMIT_FILTER_BRANCH_MASK="$TTT_WRITE_COMMIT_FILTER_BRANCH_MASK" \\
V47_TTT_SCALE_STATE_MODE="$TTT_WRITE_SCALE_STATE_MODE" \\
V47_TTT_SCALE_STATE_PROXY="$TTT_WRITE_SCALE_STATE_PROXY" \\
V47_TTT_SCALE_STATE_CARRIER="$TTT_WRITE_SCALE_STATE_CARRIER" \\
V47_TTT_SCALE_STATE_ALPHA="$TTT_WRITE_SCALE_STATE_ALPHA" \\
V47_TTT_SCALE_STATE_BRANCH_MASK="$TTT_WRITE_SCALE_STATE_BRANCH_MASK" \\
V47_TTT_SCALE_STATE_SAMPLE_TOKENS="$TTT_WRITE_SCALE_STATE_SAMPLE_TOKENS" \\
V47_ONLINE_SCALE_STATE_MODE="$ONLINE_SCALE_STATE_MODE" \\
V47_ONLINE_SCALE_STATE_MIN="$ONLINE_SCALE_STATE_MIN" \\
V47_ONLINE_SCALE_STATE_MAX="$ONLINE_SCALE_STATE_MAX" \\
V47_ENABLE_SWA_WRITE_CONTROL="$ENABLE_SWA_WRITE_CONTROL" \\
V47_SWA_WRITE_MODE="$SWA_WRITE_MODE" \\
V47_SWA_WRITE_RHO="$SWA_WRITE_RHO" \\
V47_SWA_WRITE_MIN_GATE="$SWA_WRITE_MIN_GATE" \\
V47_SWA_WRITE_SPARSE_RATIO="$SWA_WRITE_SPARSE_RATIO" \\
V47_SWA_WRITE_LAYER_MODE="$SWA_WRITE_LAYER_MODE" \\
V47_SWA_WRITE_SINGLE_LAYER="$SWA_WRITE_SINGLE_LAYER" \\
V47_SWA_WRITE_SCOPE="$SWA_WRITE_SCOPE" \\
V47_SWA_WRITE_KEEP_SCOPE="$SWA_WRITE_KEEP_SCOPE" \\
V47_SWA_WRITE_SCORE_SOURCE="$SWA_WRITE_SCORE_SOURCE" \\
V47_SWA_WRITE_CACHE_BLEND_ALPHA="$SWA_WRITE_CACHE_BLEND_ALPHA" \\
V47_SWA_WRITE_CACHE_BLEND_MODE="$SWA_WRITE_CACHE_BLEND_MODE" \\
V47_SWA_WRITE_CACHE_BLEND_TARGET="$SWA_WRITE_CACHE_BLEND_TARGET" \\
V47_ENABLE_SWA_OVERLAP_SOURCE_GATE="$ENABLE_SWA_OVERLAP_SOURCE_GATE" \\
V47_SWA_OVERLAP_SOURCE_GATE_RHO="$SWA_OVERLAP_SOURCE_GATE_RHO" \\
V47_SWA_OVERLAP_SOURCE_GATE_MIN="$SWA_OVERLAP_SOURCE_GATE_MIN" \\
V47_SWA_OVERLAP_SOURCE_GATE_MODE="$SWA_OVERLAP_SOURCE_GATE_MODE" \\
V47_SWA_OVERLAP_SOURCE_GATE_TARGET="$SWA_OVERLAP_SOURCE_GATE_TARGET" \\
V47_SWA_OVERLAP_SOURCE_GATE_LAYER_MODE="$SWA_OVERLAP_SOURCE_GATE_LAYER_MODE" \\
V47_SWA_OVERLAP_SOURCE_GATE_SINGLE_LAYER="$SWA_OVERLAP_SOURCE_GATE_SINGLE_LAYER" \\
V47_ENABLE_SWA_OVERLAP_SOURCE_REPLACE="$ENABLE_SWA_OVERLAP_SOURCE_REPLACE" \\
V47_SWA_OVERLAP_SOURCE_REPLACE_ALPHA="$SWA_OVERLAP_SOURCE_REPLACE_ALPHA" \\
V47_SWA_OVERLAP_SOURCE_REPLACE_MODE="$SWA_OVERLAP_SOURCE_REPLACE_MODE" \\
V47_SWA_OVERLAP_SOURCE_REPLACE_TARGET="$SWA_OVERLAP_SOURCE_REPLACE_TARGET" \\
V47_SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE="$SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE" \\
V47_SWA_OVERLAP_SOURCE_REPLACE_SINGLE_LAYER="$SWA_OVERLAP_SOURCE_REPLACE_SINGLE_LAYER" \\
V47_STAGE_C_MODE="$STAGE_C_MODE" \\
V47_STAGE_C_CACHE_DIR="$STAGE_C_CACHE_DIR" \\
V47_STAGE_C_CACHE_MODE="$STAGE_C_CACHE_MODE" \\
V47_STAGE_C_CACHE_REQUIRE_HIT="$STAGE_C_CACHE_REQUIRE_HIT" \\
V47_STAGE_C_CACHE_VALIDATE="$STAGE_C_CACHE_VALIDATE" \\
V47_HMC_IGNORE_SEMANTIC_PRIOR="$HMC_IGNORE_SEMANTIC_PRIOR" \\
V47_EMPTY_CUDA_CACHE_EACH_CHUNK="$EMPTY_CUDA_CACHE_EACH_CHUNK" \\
V47_SEMANTIC_ROLE_POLICY="$SEMANTIC_ROLE_POLICY" \\
V47_SEMANTIC_MEMORY_PATHS="$SEMANTIC_MEMORY_PATHS" \\
V47_SEMANTIC_ROLE_HIGHD_QUANTILE="$SEMANTIC_ROLE_HIGHD_QUANTILE" \\
V47_SEMANTIC_ROLE_LOW_TRUST="$SEMANTIC_ROLE_LOW_TRUST" \\
V47_SEMANTIC_ROLE_POSITIVE_SCALE="$SEMANTIC_ROLE_POSITIVE_SCALE" \\
V47_SEMANTIC_ROLE_NEUTRAL_SCALE="$SEMANTIC_ROLE_NEUTRAL_SCALE" \\
V47_SEMANTIC_ROLE_NEGATIVE_SCALE="$SEMANTIC_ROLE_NEGATIVE_SCALE" \\
V47_SEMANTIC_ROLE_SWA_NEGATIVE_SCALE="$SEMANTIC_ROLE_SWA_NEGATIVE_SCALE" \\
V47_SEMANTIC_ROLE_SWA_PROTECT_SCALE="$SEMANTIC_ROLE_SWA_PROTECT_SCALE" \\
V47_SEMANTIC_ROLE_CONTROL_MODE="$SEMANTIC_ROLE_CONTROL_MODE" \\
V47_SEMANTIC_ROLE_CONTROL_SEED="$SEMANTIC_ROLE_CONTROL_SEED" \\
ENABLE_CONTEXT_SOURCE_SKIP="${ENABLE_CONTEXT_SOURCE_SKIP:-0}" \\
CONTEXT_SOURCE_SKIP_IMPL="${CONTEXT_SOURCE_SKIP_IMPL:-bias}" \\
CONTEXT_SOURCE_SKIP_SCOPE="${CONTEXT_SOURCE_SKIP_SCOPE:-frame}" \\
CONTEXT_SOURCE_SKIP_MODE="${CONTEXT_SOURCE_SKIP_MODE:-hard}" \\
CONTEXT_SOURCE_SKIP_MASK="${CONTEXT_SOURCE_SKIP_MASK:-dg_q90}" \\
CONTEXT_SOURCE_SKIP_LAYER_MODE="${CONTEXT_SOURCE_SKIP_LAYER_MODE:-early}" \\
CONTEXT_SOURCE_SKIP_SINGLE_LAYER="${CONTEXT_SOURCE_SKIP_SINGLE_LAYER:-}" \\
CONTEXT_SOURCE_SKIP_SOFT_RHO="${CONTEXT_SOURCE_SKIP_SOFT_RHO:-0.5}" \\
CONTEXT_SOURCE_SKIP_SOFT_MIN_KEEP="${CONTEXT_SOURCE_SKIP_SOFT_MIN_KEEP:-0.5}" \\
CONTEXT_SOURCE_SKIP_RECORD_ATTENTION_MASS="${CONTEXT_SOURCE_SKIP_RECORD_ATTENTION_MASS:-0}" \\
tools/run_v47_adaptive_ttt_writer_candidate.sh "$GPU" "$ROW" "$RUN_NAME"
EOF
chmod +x "$OUT/reproduce_command.sh"
cp "$OUT/reproduce_command.sh" "$OUT/v47_reproduce_command.sh"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] START $RUN_NAME row=$ROW gpu=$GPU" | tee "$OUT/run_status.txt"
tools/run_attention_cue_experiment.sh "$GPU" "$RUN_NAME" "$MODE" "$CUE" "$BETA" "$WRITE_SCORE"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] DONE $RUN_NAME row=$ROW gpu=$GPU" | tee -a "$OUT/run_status.txt"
