#!/usr/bin/env bash
set -euo pipefail

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
cd "$ROOT"

BASE="${ATTN_CUE_BASE:-results/kitti01_hmc_v2/acl2_v66b_dense_semantic_scale/phase9_parallel_continuation/rollouts}"
mkdir -p "$BASE"
END_FRAME_VALUE="${END_FRAME:-96}"
RUN_TAG="${RUN_TAG:-FIX3_MODE}"
RUN_SUFFIX="${RUN_SUFFIX:-_96F}"
RUN_PREFIX="${RUN_PREFIX:-V66B_P9_TTT_SWA_OVERLAP_${RUN_TAG}}"

COMMON_ENV=(
  ATTN_CUE_BASE="$BASE"
  END_FRAME="$END_FRAME_VALUE"
  STAGE_C_MODE=reference
  STAGE_C_CACHE_DIR=results/kitti_preprocess/01/stage_c_cache_semantic_chunks
  STAGE_C_CACHE_MODE=read
  STAGE_C_CACHE_REQUIRE_HIT=1
  STAGE_C_CACHE_VALIDATE=0
  STAGE_C_INLINE_WHEN_IGNORED=0
  SEMANTIC_PRIOR_MODE=spg_v2
  HMC_IGNORE_SEMANTIC_PRIOR=0
  SEMANTIC_ROLE_POLICY=causal_fg_semantic_risk_skip
  SEMANTIC_MEMORY_PATHS=swa
  SEMANTIC_ROLE_SWA_NEGATIVE_SCALE=1.0
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.25
  READ_PATH=frame
  FRAME_BIAS_MODE=pair
  BETA_SWA=4.75
  RESET_EVERY=5
  TTT_WRITE_POST_ZP_SUMMARY=1
  CONTEXT_SOURCE_SKIP_RECORD_ATTENTION_MASS=1
  CONTEXT_SOURCE_SKIP_ATTENTION_MASS_MAX_QUERIES=256
  ENABLE_SWA_OVERLAP_SOURCE_GATE=0
  SWA_OVERLAP_SOURCE_GATE_RHO=0.0
  SWA_OVERLAP_SOURCE_GATE_MIN=0.50
  SWA_OVERLAP_SOURCE_GATE_MODE=source
  SWA_OVERLAP_SOURCE_GATE_TARGET=v
  SWA_OVERLAP_SOURCE_GATE_LAYER_MODE=last
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=0
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.0
  SWA_OVERLAP_SOURCE_REPLACE_MODE=source
  SWA_OVERLAP_SOURCE_REPLACE_TARGET=kv
  SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE=last
)

run_job() {
  local gpu="$1"
  local run_name="$2"
  shift 2
  (
    set -x
    env "${COMMON_ENV[@]}" "$@" \
      bash tools/run_attention_cue_experiment.sh "$gpu" "$run_name" hybrid dyn 4.75 stage_d
  ) &
}

# FIX3 probes two plan blockers:
# 1) scale/future proxy improved but ATE worsened: reduce source-mode strength by
#    using a softer static-anchor protect scale of 0.5, with same-mass random.
# 2) random same-mass is competitive: use overlap intersection mode so a source
#    token is suppressed/replaced only when source and current overlap both look risky.
run_job 0 "${RUN_PREFIX}_GATE_SOURCE_P050_SEM_RHO050${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_MODE=source \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.50 \
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.50 \
  SEMANTIC_ROLE_CONTROL_MODE=none

run_job 1 "${RUN_PREFIX}_GATE_SOURCE_P050_RANDOM_RHO050${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_MODE=source \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.50 \
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.50 \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345

run_job 2 "${RUN_PREFIX}_GATE_INTER_P025_SEM_RHO075${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_MODE=intersection \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.75 \
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.25 \
  SEMANTIC_ROLE_CONTROL_MODE=none

run_job 3 "${RUN_PREFIX}_GATE_INTER_P025_RANDOM_RHO075${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_MODE=intersection \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.75 \
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.25 \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345

run_job 4 "${RUN_PREFIX}_REPLACE_INTER_P025_SEM_A030${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_MODE=intersection \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.30 \
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.25 \
  SEMANTIC_ROLE_CONTROL_MODE=none

run_job 5 "${RUN_PREFIX}_REPLACE_INTER_P025_RANDOM_A030${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_MODE=intersection \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.30 \
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.25 \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345

wait

echo "[$(date '+%F %T')] all v66b phase13 FIX3 SWA mode-sweep jobs finished"
