#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 3 ]; then
  echo "Usage: $0 GPU CANDIDATE_ID CHUNK_ID" >&2
  exit 2
fi

GPU="$1"
CANDIDATE_ID="$2"
CHUNK_ID="$3"

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
V16_ROOT="${V16_ROOT:-results/kitti01_hmc_v2/acl2_v16_ttt_causalfork_candidatebank_target25}"
PHASE1="$V16_ROOT/phase1_causalfork"
ROLLOUT_BASE="$V16_ROOT/phase2_candidate_bank/rollouts"

case "$CHUNK_ID" in
  5) START_FRAME=145; END_FRAME=264; SNAP="005"; BASE_GAMMA="0.005" ;;
  6) START_FRAME=174; END_FRAME=293; SNAP="006"; BASE_GAMMA="0.005" ;;
  9) START_FRAME=261; END_FRAME=380; SNAP="009"; BASE_GAMMA="0.005" ;;
  10) START_FRAME=290; END_FRAME=409; SNAP="010"; BASE_GAMMA="0.003" ;;
  12) START_FRAME=348; END_FRAME=467; SNAP="012"; BASE_GAMMA="0.003" ;;
  16) START_FRAME=464; END_FRAME=583; SNAP="016"; BASE_GAMMA="0.0003" ;;
  *) echo "Unsupported CHUNK_ID: $CHUNK_ID" >&2; exit 2 ;;
esac

BASE_GAMMAS="5:0.005,6:0.005,7:0.005,8:0.005,9:0.005,10:0.003,11:0.003,12:0.003,16:0.0003"
BASE_TRI_PARAMS="5:0.35/0.12/0.85,6:0.35/0.12/0.85,7:0.35/0.12/0.85,8:0.35/0.12/0.85,9:0.35/0.12/0.85,10:0.35/0.12/0.85,11:0.35/0.12/0.85,12:0.35/0.12/0.85,16:0.35/0.08/0.85"
CHUNK_GAMMAS="$BASE_GAMMAS"

case "$CANDIDATE_ID" in
  K1_H9)
    ;;
  K4_TTGR_ZERO)
    CHUNK_GAMMAS="${BASE_GAMMAS/${CHUNK_ID}:${BASE_GAMMA}/${CHUNK_ID}:0.0}"
    ;;
  K4_TTGR_DOUBLE)
    NEW_GAMMA="$("$ROOT"/tools/v16_candidate_value.py double "$BASE_GAMMA")"
    CHUNK_GAMMAS="${BASE_GAMMAS/${CHUNK_ID}:${BASE_GAMMA}/${CHUNK_ID}:${NEW_GAMMA}}"
    ;;
  K7_EMA090_W0)
    export TTT_WRITE_COMMIT_EMA_ALPHA=0.90
    export TTT_WRITE_COMMIT_EMA_BRANCH_MASK=0
    export TTT_WRITE_COMMIT_EMA_CHUNKS="$CHUNK_ID"
    ;;
  K8_NATIVE_MIX075_W0)
    export TTT_WRITE_NATIVE_MIX_SCALES="0.75,1.00,1.00"
    ;;
  K5_CAP_W0_050)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=cap
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_CAP_RATIO=0.50
    ;;
  K10_DUAL_K2_A025)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.75
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.25
    export TTT_WRITE_TRANSIENT_DELTA_TTL=2
    ;;
  K9_OVERLAP_PSEUDO_KV)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_replay_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  K11_ORTHO_SUPPRESS_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  K12_OVERLAP_STATIC_TOPK)
    export TTT_WRITE_REPLAY_TOKEN_FILTER_MODE=overlap_static_topk
    export TTT_WRITE_REPLAY_TOKEN_FILTER_RATIO=0.50
    export TTT_WRITE_REPLAY_TOKEN_FILTER_SCOPE=both_overlap
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BRANCH_MASK=0
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BLEND=1.0
    ;;
  K13_ORTHO_RHO025_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.25
    ;;
  K14_TTGR_ZERO_ORTHO_W0)
    CHUNK_GAMMAS="${BASE_GAMMAS/${CHUNK_ID}:${BASE_GAMMA}/${CHUNK_ID}:0.0}"
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  K15_COSCAP_W0_025_050)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=cosine_cap
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_MIN_COS=0.25
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.25
    export TTT_WRITE_NATIVE_DELTA_GATE_CAP_RATIO=0.50
    ;;
  K16_COMMIT_CONFLICT_NATIVE025)
    export TTT_WRITE_COMMIT_FILTER_MODE=native_to_candidate_by_risk
    export TTT_WRITE_COMMIT_FILTER_RISK_SOURCE=ttt_update_conflict_energy
    export TTT_WRITE_COMMIT_FILTER_SCOPE=both_overlap
    export TTT_WRITE_COMMIT_FILTER_STAT=mean
    export TTT_WRITE_COMMIT_FILTER_BASE=0.25
    export TTT_WRITE_COMMIT_FILTER_GAIN=0.75
    export TTT_WRITE_COMMIT_FILTER_MIN=0.0
    export TTT_WRITE_COMMIT_FILTER_MAX=1.0
    export TTT_WRITE_COMMIT_FILTER_BRANCH_MASK=0
    export TTT_WRITE_COMMIT_FILTER_CHUNKS="$CHUNK_ID"
    ;;
  K17_COMMIT_CONFLICT_NATIVE050_Q90)
    export TTT_WRITE_COMMIT_FILTER_MODE=native_to_candidate_by_risk
    export TTT_WRITE_COMMIT_FILTER_RISK_SOURCE=ttt_update_conflict_energy
    export TTT_WRITE_COMMIT_FILTER_SCOPE=both_overlap
    export TTT_WRITE_COMMIT_FILTER_STAT=q90
    export TTT_WRITE_COMMIT_FILTER_BASE=0.50
    export TTT_WRITE_COMMIT_FILTER_GAIN=0.50
    export TTT_WRITE_COMMIT_FILTER_MIN=0.0
    export TTT_WRITE_COMMIT_FILTER_MAX=1.0
    export TTT_WRITE_COMMIT_FILTER_BRANCH_MASK=0
    export TTT_WRITE_COMMIT_FILTER_CHUNKS="$CHUNK_ID"
    ;;
  K18_OVERLAP_PSEUDO_V050)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_replay_v
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  K19_ORTHO_SUPPRESS_W1)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=1
    ;;
  K20_ORTHO_SUPPRESS_W2)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=2
    ;;
  K21_ORTHO_SUPPRESS_ALL)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=all
    ;;
  K22_GT_SCALE_PROJ_BASE)
    export TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE=gt_scale_projection
    export V11_PROJECTION_ACTION_MODE=gt_scale_projection
    export V11_PROJECTION_ACTION_CHUNKS="$CHUNK_ID"
    export V11_PROJECTION_ACTION_STRENGTH=1.0
    ;;
  K23_GT_SCALE_PROJ_STR2)
    export TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE=gt_scale_projection
    export V11_PROJECTION_ACTION_MODE=gt_scale_projection
    export V11_PROJECTION_ACTION_CHUNKS="$CHUNK_ID"
    export V11_PROJECTION_ACTION_STRENGTH=2.0
    ;;
  K24_GT_SCALE_PROJ_DOUBLE)
    NEW_GAMMA="$("$ROOT"/tools/v16_candidate_value.py double "$BASE_GAMMA")"
    CHUNK_GAMMAS="${BASE_GAMMAS/${CHUNK_ID}:${BASE_GAMMA}/${CHUNK_ID}:${NEW_GAMMA}}"
    export TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE=gt_scale_projection
    export V11_PROJECTION_ACTION_MODE=gt_scale_projection
    export V11_PROJECTION_ACTION_CHUNKS="$CHUNK_ID"
    export V11_PROJECTION_ACTION_STRENGTH=1.0
    ;;
  K25_ONLINE_SCALE_OVERLAP_STEP)
    export ONLINE_SCALE_STATE_MODE=overlap_step
    export ONLINE_SCALE_STATE_MIN=0.80
    export ONLINE_SCALE_STATE_MAX=1.25
    ;;
  K26_ONLINE_SCALE_OVERLAP_TIGHT)
    export ONLINE_SCALE_STATE_MODE=overlap_step
    export ONLINE_SCALE_STATE_MIN=0.90
    export ONLINE_SCALE_STATE_MAX=1.10
    ;;
  K27_ONLINE_SCALE_INV_STEP)
    export ONLINE_SCALE_STATE_MODE=overlap_step_inverse
    export ONLINE_SCALE_STATE_MIN=0.80
    export ONLINE_SCALE_STATE_MAX=1.25
    ;;
  K28_ONLINE_SCALE_INV_TIGHT)
    export ONLINE_SCALE_STATE_MODE=overlap_step_inverse
    export ONLINE_SCALE_STATE_MIN=0.90
    export ONLINE_SCALE_STATE_MAX=1.10
    ;;
  *)
    echo "Unsupported CANDIDATE_ID: $CANDIDATE_ID" >&2
    exit 2
    ;;
esac

RUN_NAME="V16_P2_${CANDIDATE_ID}_chunk${CHUNK_ID}_h3_globalgate_H9parent_SWKS3"

env \
  KITTI_SEQ=01 \
  ATTN_CUE_BASE="$ROLLOUT_BASE" \
  START_FRAME="$START_FRAME" \
  END_FRAME="$END_FRAME" \
  GLOBAL_CHUNK_OFFSET="$CHUNK_ID" \
  RESET_EVERY=5 \
  WRITE_ALPHA=0.125 \
  READ_LAYER_MODE=all \
  READ_BETA_FRAME_CHUNKS="5:4.85,6:4.85,7:4.85,8:4.85,9:4.85,10:4.25,11:4.25,12:4.25,16:4.25" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.5 \
  SWA_OVERLAP_SOURCE_REPLACE_MODE=source \
  ENABLE_SWA_WRITE_CONTROL=1 \
  SWA_WRITE_LAYER_MODE=last \
  SWA_WRITE_KEEP_SCOPE=both_overlap \
  TTT_WRITE_GRADIENT_REVERSAL_MODE=tri_replay \
  TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE=update_conflict_energy \
  TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS="$CHUNK_GAMMAS" \
  TTT_WRITE_NATIVE_MIX_SCALES="${TTT_WRITE_NATIVE_MIX_SCALES:-1.10,1.00,1.00}" \
  TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC=0.35 \
  TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC=0.12 \
  TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA=0.85 \
  TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS="$BASE_TRI_PARAMS" \
  LOAD_HMC_STATE_AT_CHUNK="$PHASE1/state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_HMC_STATE_AT_CHUNK_INDEX=0 \
  LOAD_MERGE_STATE_AT_CHUNK="$PHASE1/merge_state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_MERGE_STATE_AT_CHUNK_INDEX=0 \
  "$ROOT/tools/run_attention_cue_experiment.sh" \
  "$GPU" "$RUN_NAME" hybrid acl2.gg.qq.low.g2_3.past_only.headmean.robustq 4.75 stage_d_x_dg_inv_sqrt
