#!/usr/bin/env bash
set -euo pipefail

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
cd "$ROOT"

BASE="${ATTN_CUE_BASE:-results/kitti01_hmc_v2/acl2_v66b_dense_semantic_scale/phase9_parallel_continuation/rollouts}"
mkdir -p "$BASE"
END_FRAME_VALUE="${END_FRAME:-96}"
RUN_TAG="${RUN_TAG:-SELECTOR_RULE}"
RUN_SUFFIX="${RUN_SUFFIX-_96F}"
RUN_PREFIX="${RUN_PREFIX:-V66B_P9_TTT_${RUN_TAG}}"
BASE_RUN_NAME="${BASE_RUN_NAME:-V66B_P9_TTT_BASE_DENSE_IGNORE_${RUN_TAG}${RUN_SUFFIX}}"
SELECTOR_CHUNKS="${SELECTOR_CHUNKS:-3,4,5,6,7,16,17,20,21,22,23,26,27,33,36}"

COMMON_ENV=(
  ATTN_CUE_BASE="$BASE"
  END_FRAME="$END_FRAME_VALUE"
  STAGE_C_MODE=reference
  STAGE_C_CACHE_DIR=results/kitti_preprocess/01/stage_c_cache_semantic_chunks
  STAGE_C_CACHE_MODE=read
  STAGE_C_CACHE_REQUIRE_HIT=1
  STAGE_C_CACHE_VALIDATE=0
  STAGE_C_INLINE_WHEN_IGNORED=0
  SEMANTIC_PRIOR_MODE=spg_v2
  HMC_IGNORE_SEMANTIC_PRIOR=0
  SEMANTIC_ROLE_POLICY=causal_fg_semantic_risk_skip
  SEMANTIC_MEMORY_PATHS=ttt
  READ_PATH=frame
  FRAME_BIAS_MODE=pair
  BETA_SWA=4.75
  RESET_EVERY=5
  TTT_WRITE_POST_ZP_SUMMARY=1
  CONTEXT_SOURCE_SKIP_RECORD_ATTENTION_MASS=1
  CONTEXT_SOURCE_SKIP_ATTENTION_MASS_MAX_QUERIES=256
)

run_job() {
  local gpu="$1"
  local run_name="$2"
  shift 2
  (
    set -x
    env "${COMMON_ENV[@]}" "$@" \
      bash tools/run_attention_cue_experiment.sh "$gpu" "$run_name" hybrid dyn 4.75 stage_d
  ) &
}

# Selector rule source:
# results/.../phase14_phase34_causal_selector/phase3_selector_rule_summary.json
# fixed rule: base_mass >= 71723 AND vertical_plus_boundary_condition >= 0.000966918
# selected chunks: 3,4,5,6,7,16,17,20,21,22,23,26,27,33,36
#
# HARD reuses prior role-extreme TTT scales. SOFT reduces perturbation strength
# because previous active/gate attempts often improved a proxy but hurt ATE.
run_job 0 "$BASE_RUN_NAME" \
  HMC_IGNORE_SEMANTIC_PRIOR=1 \
  STAGE_C_INLINE_WHEN_IGNORED=1 \
  SEMANTIC_ROLE_POLICY=none \
  SEMANTIC_MEMORY_PATHS=

run_job 1 "${RUN_PREFIX}_HARD_SEM${RUN_SUFFIX}" \
  SEMANTIC_ACTION_ACTIVE_CHUNKS="$SELECTOR_CHUNKS" \
  SEMANTIC_ROLE_CONTROL_MODE=none \
  SEMANTIC_ROLE_CONTROL_SEED=12345 \
  SEMANTIC_ROLE_POSITIVE_SCALE=1.50 \
  SEMANTIC_ROLE_NEUTRAL_SCALE=0.50 \
  SEMANTIC_ROLE_NEGATIVE_SCALE=0.00

run_job 2 "${RUN_PREFIX}_HARD_RANDOMCTRL_S12345${RUN_SUFFIX}" \
  SEMANTIC_ACTION_ACTIVE_CHUNKS="$SELECTOR_CHUNKS" \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345 \
  SEMANTIC_ROLE_POSITIVE_SCALE=1.50 \
  SEMANTIC_ROLE_NEUTRAL_SCALE=0.50 \
  SEMANTIC_ROLE_NEGATIVE_SCALE=0.00

run_job 3 "${RUN_PREFIX}_HARD_SHUFFLECTRL_S12345${RUN_SUFFIX}" \
  SEMANTIC_ACTION_ACTIVE_CHUNKS="$SELECTOR_CHUNKS" \
  SEMANTIC_ROLE_CONTROL_MODE=shuffled_semantic \
  SEMANTIC_ROLE_CONTROL_SEED=12345 \
  SEMANTIC_ROLE_POSITIVE_SCALE=1.50 \
  SEMANTIC_ROLE_NEUTRAL_SCALE=0.50 \
  SEMANTIC_ROLE_NEGATIVE_SCALE=0.00

run_job 4 "${RUN_PREFIX}_SOFT_SEM${RUN_SUFFIX}" \
  SEMANTIC_ACTION_ACTIVE_CHUNKS="$SELECTOR_CHUNKS" \
  SEMANTIC_ROLE_CONTROL_MODE=none \
  SEMANTIC_ROLE_CONTROL_SEED=12345 \
  SEMANTIC_ROLE_POSITIVE_SCALE=1.25 \
  SEMANTIC_ROLE_NEUTRAL_SCALE=0.75 \
  SEMANTIC_ROLE_NEGATIVE_SCALE=0.25

run_job 5 "${RUN_PREFIX}_SOFT_RANDOMCTRL_S12345${RUN_SUFFIX}" \
  SEMANTIC_ACTION_ACTIVE_CHUNKS="$SELECTOR_CHUNKS" \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345 \
  SEMANTIC_ROLE_POSITIVE_SCALE=1.25 \
  SEMANTIC_ROLE_NEUTRAL_SCALE=0.75 \
  SEMANTIC_ROLE_NEGATIVE_SCALE=0.25

wait

echo "[$(date '+%F %T')] all v66b selector-rule TTT jobs finished"
