#!/usr/bin/env bash
set -euo pipefail

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
cd "$ROOT"

BASE="${ATTN_CUE_BASE:-results/kitti01_hmc_v2/acl2_v66b_dense_semantic_scale/phase9_parallel_continuation/rollouts}"
mkdir -p "$BASE"
END_FRAME_VALUE="${END_FRAME:-96}"

if [ -z "${RUN_PREFIX:-}" ]; then
  if [ "$END_FRAME_VALUE" = "704" ]; then
    RUN_PREFIX="V66B_P9_704_TTT_SWA_OVERLAP"
    BASE_RUN_NAME="V66B_P9_704_TTT_BASE_DENSE_IGNORE_SWA"
    RUN_SUFFIX=""
  else
    RUN_PREFIX="V66B_P9_TTT_SWA_OVERLAP"
    BASE_RUN_NAME="V66B_P9_TTT_BASE_DENSE_IGNORE_SWA_96F"
    RUN_SUFFIX="_96F"
  fi
else
  BASE_RUN_NAME="${BASE_RUN_NAME:-${RUN_PREFIX}_BASE_DENSE_IGNORE}"
  RUN_SUFFIX="${RUN_SUFFIX:-}"
fi

COMMON_ENV=(
  ATTN_CUE_BASE="$BASE"
  END_FRAME="$END_FRAME_VALUE"
  STAGE_C_MODE=reference
  STAGE_C_CACHE_DIR=results/kitti_preprocess/01/stage_c_cache_semantic_chunks
  STAGE_C_CACHE_MODE=read
  STAGE_C_CACHE_REQUIRE_HIT=1
  STAGE_C_CACHE_VALIDATE=0
  STAGE_C_INLINE_WHEN_IGNORED=0
  SEMANTIC_PRIOR_MODE=spg_v2
  HMC_IGNORE_SEMANTIC_PRIOR=0
  SEMANTIC_ROLE_POLICY=causal_fg_semantic_risk_skip
  SEMANTIC_MEMORY_PATHS=swa
  SEMANTIC_ROLE_SWA_NEGATIVE_SCALE=1.0
  SEMANTIC_ROLE_SWA_PROTECT_SCALE=0.0
  READ_PATH=frame
  FRAME_BIAS_MODE=pair
  BETA_SWA=4.75
  RESET_EVERY=5
  TTT_WRITE_POST_ZP_SUMMARY=1
  CONTEXT_SOURCE_SKIP_RECORD_ATTENTION_MASS=1
  CONTEXT_SOURCE_SKIP_ATTENTION_MASS_MAX_QUERIES=256
  ENABLE_SWA_OVERLAP_SOURCE_GATE=0
  SWA_OVERLAP_SOURCE_GATE_RHO=0.0
  SWA_OVERLAP_SOURCE_GATE_MIN=0.50
  SWA_OVERLAP_SOURCE_GATE_MODE=source
  SWA_OVERLAP_SOURCE_GATE_TARGET=v
  SWA_OVERLAP_SOURCE_GATE_LAYER_MODE=last
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=0
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.0
  SWA_OVERLAP_SOURCE_REPLACE_MODE=source
  SWA_OVERLAP_SOURCE_REPLACE_TARGET=kv
  SWA_OVERLAP_SOURCE_REPLACE_LAYER_MODE=last
)

run_job() {
  local gpu="$1"
  local run_name="$2"
  shift 2
  (
    set -x
    env "${COMMON_ENV[@]}" "$@" \
      bash tools/run_attention_cue_experiment.sh "$gpu" "$run_name" hybrid dyn 4.75 stage_d
  ) &
}

# Phase13 tests whether semantic roles can act on the actual SWA overlap
# source carrier.  Gate suppresses risky previous-tail source tokens; replace
# blends risky previous-tail K/V toward aligned current-head K/V.  Random and
# shuffled controls perturb SWA role positions while preserving role mass.
run_job 0 "$BASE_RUN_NAME" \
  HMC_IGNORE_SEMANTIC_PRIOR=1 \
  STAGE_C_INLINE_WHEN_IGNORED=1 \
  SEMANTIC_ROLE_POLICY=none \
  SEMANTIC_MEMORY_PATHS=

run_job 1 "${RUN_PREFIX}_GATE_PROTECT_SEM_RHO050${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.50 \
  SWA_OVERLAP_SOURCE_GATE_MIN=0.50 \
  SEMANTIC_ROLE_CONTROL_MODE=none

run_job 2 "${RUN_PREFIX}_GATE_PROTECT_RANDOM_RHO050${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.50 \
  SWA_OVERLAP_SOURCE_GATE_MIN=0.50 \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345

run_job 3 "${RUN_PREFIX}_GATE_PROTECT_SHUFFLE_RHO050${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_GATE=1 \
  SWA_OVERLAP_SOURCE_GATE_RHO=0.50 \
  SWA_OVERLAP_SOURCE_GATE_MIN=0.50 \
  SEMANTIC_ROLE_CONTROL_MODE=shuffled_semantic \
  SEMANTIC_ROLE_CONTROL_SEED=12345

run_job 4 "${RUN_PREFIX}_REPLACE_PROTECT_SEM_A030${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.30 \
  SEMANTIC_ROLE_CONTROL_MODE=none

run_job 5 "${RUN_PREFIX}_REPLACE_PROTECT_RANDOM_A030${RUN_SUFFIX}" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.30 \
  SEMANTIC_ROLE_CONTROL_MODE=random_same_mass \
  SEMANTIC_ROLE_CONTROL_SEED=12345

wait

echo "[$(date '+%F %T')] all v66b phase13 SWA-overlap jobs finished"
