#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 GPU CANDIDATE_ID CHUNK_ID HORIZON" >&2
  exit 2
fi

GPU="$1"
CANDIDATE_ID="$2"
CHUNK_ID="$3"
HORIZON="$4"

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
V16_ROOT="${V16_ROOT:-results/kitti01_hmc_v2/acl2_v16_ttt_causalfork_candidatebank_target25}"
V19_ROOT="${V19_ROOT:-results/kitti01_hmc_v2/acl2_v19_ttt_trajectory_state_write_reboot_target25}"
PHASE1="$V16_ROOT/phase1_causalfork"
ROLLOUT_BASE="$V19_ROOT/rollouts"

case "$HORIZON" in
  3|5|8|10|15) ;;
  *) echo "Unsupported HORIZON: $HORIZON" >&2; exit 2 ;;
esac

case "$CHUNK_ID" in
  5) START_FRAME=145; SNAP="005" ;;
  6) START_FRAME=174; SNAP="006" ;;
  9) START_FRAME=261; SNAP="009" ;;
  10) START_FRAME=290; SNAP="010" ;;
  12) START_FRAME=348; SNAP="012" ;;
  16) START_FRAME=464; SNAP="016" ;;
  *) echo "Unsupported CHUNK_ID: $CHUNK_ID" >&2; exit 2 ;;
esac

END_FRAME=$((START_FRAME + 32 + HORIZON * 29))
ACTIVE_SCALE_CHUNKS="${TTT_WRITE_SCALE_STATE_CHUNKS:-$CHUNK_ID-$((CHUNK_ID + HORIZON))}"

BASE_GAMMAS="5:0.005,6:0.005,7:0.005,8:0.005,9:0.005,10:0.003,11:0.003,12:0.003,13:0.003,14:0.003,15:0.003,16:0.0003"
BASE_TRI_PARAMS="5:0.35/0.12/0.85,6:0.35/0.12/0.85,7:0.35/0.12/0.85,8:0.35/0.12/0.85,9:0.35/0.12/0.85,10:0.35/0.12/0.85,11:0.35/0.12/0.85,12:0.35/0.12/0.85,13:0.35/0.12/0.85,14:0.35/0.12/0.85,15:0.35/0.12/0.85,16:0.35/0.08/0.85"
CHUNK_GAMMAS="$BASE_GAMMAS"
GR_RISK_SOURCE="update_conflict_energy"

case "$CANDIDATE_ID" in
  K1_H9)
    ;;
  SCALETTT_01_SPECIAL_TOKEN_W0_A005)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=special_token
    export TTT_WRITE_SCALE_STATE_ALPHA=0.05
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALETTT_02_STRUCTURE_LOWDG_W0_A005)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=structure_lowdg
    export TTT_WRITE_SCALE_STATE_ALPHA=0.05
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALETTT_03_OVERLAP_STATIC_W0W2_A005)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=overlap_static_anchor
    export TTT_WRITE_SCALE_STATE_ALPHA=0.05
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0,2
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALETTT_04_STRUCTURE_LOWDG_W0_A010)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=structure_lowdg
    export TTT_WRITE_SCALE_STATE_ALPHA=0.10
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALETTT_05_OVERLAP_STATIC_W0W2_A010)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=overlap_static_anchor
    export TTT_WRITE_SCALE_STATE_ALPHA=0.10
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0,2
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALECOMMIT_01_PZBASIS_HARM_W0_G025)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=structure_lowdg
    export TTT_WRITE_SCALE_STATE_ALPHA=0.25
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALECOMMIT_02_AUXGEO_OVERLAP_W0_G025)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=overlap_static_anchor
    export TTT_WRITE_SCALE_STATE_ALPHA=0.25
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.30
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.45
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  SCALECOMMIT_03_HIST_DELTA_W0_G025)
    export TTT_WRITE_SCALE_STATE_MODE=projection_risk
    export TTT_WRITE_SCALE_STATE_PROXY=pose_step_ema
    export TTT_WRITE_SCALE_STATE_CARRIER=structure_lowdg
    export TTT_WRITE_SCALE_STATE_ALPHA=0.25
    export TTT_WRITE_SCALE_STATE_BRANCH_MASK=0
    export TTT_WRITE_SCALE_STATE_CHUNKS="$ACTIVE_SCALE_CHUNKS"
    export TTT_WRITE_NATIVE_MIX_SCALES=1.20,1.00,1.00
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=cosine_soft
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.35
    GR_RISK_SOURCE="v19_scale_state"
    ;;
  *)
    echo "Unsupported CANDIDATE_ID for v19 rollout: $CANDIDATE_ID" >&2
    exit 2
    ;;
esac

RUN_PREFIX="${RUN_PREFIX:-V19_P2SCALE_R1}"
RUN_NAME="${RUN_PREFIX}_${CANDIDATE_ID}_chunk${CHUNK_ID}_h${HORIZON}_globalgate_H9parent_SWKS3"
RUN_DIR="$ROOT/$ROLLOUT_BASE/$RUN_NAME"

if [ "${FORCE:-0}" != "1" ] && [ -f "$RUN_DIR/01.txt" ] && grep -q "DONE $RUN_NAME" "$RUN_DIR/run_status.txt" 2>/dev/null; then
  echo "SKIP existing DONE run: $RUN_NAME"
  exit 0
fi

env \
  KITTI_SEQ=01 \
  ATTN_CUE_BASE="$ROLLOUT_BASE" \
  START_FRAME="$START_FRAME" \
  END_FRAME="$END_FRAME" \
  GLOBAL_CHUNK_OFFSET="$CHUNK_ID" \
  RESET_EVERY=5 \
  WRITE_ALPHA=0.125 \
  READ_LAYER_MODE=all \
  READ_BETA_FRAME_CHUNKS="5:4.85,6:4.85,7:4.85,8:4.85,9:4.85,10:4.25,11:4.25,12:4.25,13:4.25,14:4.25,15:4.25,16:4.25" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.5 \
  SWA_OVERLAP_SOURCE_REPLACE_MODE=source \
  ENABLE_SWA_WRITE_CONTROL=1 \
  SWA_WRITE_LAYER_MODE=last \
  SWA_WRITE_KEEP_SCOPE=both_overlap \
  TTT_WRITE_GRADIENT_REVERSAL_MODE=tri_replay \
  TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE="$GR_RISK_SOURCE" \
  TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS="$CHUNK_GAMMAS" \
  TTT_WRITE_NATIVE_MIX_SCALES="${TTT_WRITE_NATIVE_MIX_SCALES:-1.10,1.00,1.00}" \
  TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC=0.35 \
  TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC=0.12 \
  TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA=0.85 \
  TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS="$BASE_TRI_PARAMS" \
  LOAD_HMC_STATE_AT_CHUNK="$PHASE1/state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_HMC_STATE_AT_CHUNK_INDEX=0 \
  LOAD_MERGE_STATE_AT_CHUNK="$PHASE1/merge_state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_MERGE_STATE_AT_CHUNK_INDEX=0 \
  "$ROOT/tools/run_attention_cue_experiment.sh" \
  "$GPU" "$RUN_NAME" hybrid acl2.gg.qq.low.g2_3.past_only.headmean.robustq 4.75 stage_d_x_dg_inv_sqrt
