#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 GPU CANDIDATE_ID CHUNK_ID HORIZON" >&2
  exit 2
fi

GPU="$1"
CANDIDATE_ID="$2"
CHUNK_ID="$3"
HORIZON="$4"

ROOT="${LOGER_ROOT:-/mnt/data/users/chengshun.wang/pjs/LoGeR}"
V16_ROOT="${V16_ROOT:-results/kitti01_hmc_v2/acl2_v16_ttt_causalfork_candidatebank_target25}"
V17_ROOT="${V17_ROOT:-results/kitti01_hmc_v2/acl2_v17_ttt_write_causalstate_reboot_target25}"
PHASE1="$V16_ROOT/phase1_causalfork"
ROLLOUT_BASE="$V17_ROOT/phase1_horizon/rollouts"
MERGE_SAVE_BASE="$V17_ROOT/phase1_horizon/merge_state_snapshots"
SAVE_CANDIDATE_MERGE_STATES="${SAVE_CANDIDATE_MERGE_STATES:-0}"

case "$HORIZON" in
  3|5|8|10) ;;
  *) echo "Unsupported HORIZON: $HORIZON" >&2; exit 2 ;;
esac

case "$CHUNK_ID" in
  5) START_FRAME=145; SNAP="005"; BASE_GAMMA="0.005" ;;
  6) START_FRAME=174; SNAP="006"; BASE_GAMMA="0.005" ;;
  9) START_FRAME=261; SNAP="009"; BASE_GAMMA="0.005" ;;
  10) START_FRAME=290; SNAP="010"; BASE_GAMMA="0.003" ;;
  12) START_FRAME=348; SNAP="012"; BASE_GAMMA="0.003" ;;
  16) START_FRAME=464; SNAP="016"; BASE_GAMMA="0.0003" ;;
  *) echo "Unsupported CHUNK_ID: $CHUNK_ID" >&2; exit 2 ;;
esac

# Run one extra local chunk so the final evaluated overlap frames are merged
# with the same future context as the full causal run. Reports crop metrics
# back to the requested horizon window.
END_FRAME=$((START_FRAME + 32 + HORIZON * 29))

BASE_GAMMAS="5:0.005,6:0.005,7:0.005,8:0.005,9:0.005,10:0.003,11:0.003,12:0.003,16:0.0003"
BASE_TRI_PARAMS="5:0.35/0.12/0.85,6:0.35/0.12/0.85,7:0.35/0.12/0.85,8:0.35/0.12/0.85,9:0.35/0.12/0.85,10:0.35/0.12/0.85,11:0.35/0.12/0.85,12:0.35/0.12/0.85,16:0.35/0.08/0.85"
CHUNK_GAMMAS="$BASE_GAMMAS"

case "$CANDIDATE_ID" in
  K1_H9)
    ;;
  K11_ORTHO_SUPPRESS_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  K21_ORTHO_SUPPRESS_ALL)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=all
    ;;
  K13_ORTHO_RHO025_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.25
    ;;
  K14_TTGR_ZERO_ORTHO_W0)
    CHUNK_GAMMAS="${BASE_GAMMAS/${CHUNK_ID}:${BASE_GAMMA}/${CHUNK_ID}:0.0}"
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  BASIS_01_PROXY_HARM_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  BASIS_02_PROXY_HARM_W0_EMA090)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_COMMIT_EMA_ALPHA=0.90
    export TTT_WRITE_COMMIT_EMA_BRANCH_MASK=all
    ;;
  BASIS_03_PROXY_RHO025_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.25
    ;;
  BASIS_04_PROXY_CONFLICT_COMMIT_W0)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    export TTT_WRITE_COMMIT_FILTER_MODE=native_to_candidate_by_risk
    export TTT_WRITE_COMMIT_FILTER_RISK_SOURCE=ttt_update_conflict_energy
    export TTT_WRITE_COMMIT_FILTER_SCOPE=both_overlap
    export TTT_WRITE_COMMIT_FILTER_STAT=mean
    export TTT_WRITE_COMMIT_FILTER_BASE=0.0
    export TTT_WRITE_COMMIT_FILTER_GAIN=1.0
    export TTT_WRITE_COMMIT_FILTER_MIN=0.25
    export TTT_WRITE_COMMIT_FILTER_MAX=1.0
    export TTT_WRITE_COMMIT_FILTER_BRANCH_MASK=0
    ;;
  BASIS_05_PROXY_TTGR_ZERO_POSTZP_W0)
    CHUNK_GAMMAS="${BASE_GAMMAS/${CHUNK_ID}:${BASE_GAMMA}/${CHUNK_ID}:0.0}"
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=0
    ;;
  BASIS_06_PROXY_BRANCHSEP_W0W2)
    export TTT_WRITE_NATIVE_DELTA_GATE_MODE=orthogonal_suppress
    export TTT_WRITE_NATIVE_DELTA_GATE_BRANCH_MASK=all
    export TTT_WRITE_NATIVE_DELTA_GATE_FALLBACK=0.25
    export TTT_WRITE_NATIVE_MIX_SCALES=1.10,1.00,0.75
    ;;
  AUXGEO_01_PROXY_OVERLAP_V_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_v
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_02_PROXY_OVERLAP_KV_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_03_PROXY_STRUCT_KV_W0W2)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0,2
    ;;
  AUXGEO_04_PROXY_BODY_WEAK_V_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_v
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.15
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_05_PROXY_EXIT_STRONG_KV_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.35
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    ;;
  AUXGEO_06_PROXY_STATIC_TOPK_KV_W0)
    export TTT_WRITE_REPLAY_FEATURE_GATE_MODE=overlap_pseudo_kv
    export TTT_WRITE_REPLAY_FEATURE_GATE_RHO=0.25
    export TTT_WRITE_REPLAY_FEATURE_GATE_MIN=0.50
    export TTT_WRITE_REPLAY_FEATURE_GATE_BRANCH_MASK=0
    export TTT_WRITE_REPLAY_TOKEN_FILTER_MODE=overlap_static_topk
    export TTT_WRITE_REPLAY_TOKEN_FILTER_RATIO=0.50
    export TTT_WRITE_REPLAY_TOKEN_FILTER_SCOPE=both_overlap
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BRANCH_MASK=0
    ;;
  DLBANK_01_SHORT_CONFLICT_TAU2_W0)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.50
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.75
    export TTT_WRITE_TRANSIENT_DELTA_TTL=2
    ;;
  DLBANK_02_SHORT_CONFLICT_TAU3_W0)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.35
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.60
    export TTT_WRITE_TRANSIENT_DELTA_TTL=3
    ;;
  DLBANK_03_STRUCTURE_LONG_SHORT_REST)
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_MODE=dual_lifetime
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_BRANCH_MASK=0,2
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_LONG_SCALE=0.65
    export TTT_WRITE_GRADIENT_REVERSAL_TRANSIENT_APPLY_SCALE=0.50
    export TTT_WRITE_TRANSIENT_DELTA_TTL=2
    export TTT_WRITE_REPLAY_TOKEN_FILTER_MODE=overlap_static_topk
    export TTT_WRITE_REPLAY_TOKEN_FILTER_RATIO=0.50
    export TTT_WRITE_REPLAY_TOKEN_FILTER_SCOPE=both_overlap
    export TTT_WRITE_REPLAY_TOKEN_FILTER_BRANCH_MASK=0
    ;;
  K25_ONLINE_SCALE_OVERLAP_STEP)
    export ONLINE_SCALE_STATE_MODE=overlap_step
    export ONLINE_SCALE_STATE_MIN=0.80
    export ONLINE_SCALE_STATE_MAX=1.25
    ;;
  K26_ONLINE_SCALE_OVERLAP_TIGHT)
    export ONLINE_SCALE_STATE_MODE=overlap_step
    export ONLINE_SCALE_STATE_MIN=0.90
    export ONLINE_SCALE_STATE_MAX=1.10
    ;;
  *)
    echo "Unsupported CANDIDATE_ID for v17 Phase 1: $CANDIDATE_ID" >&2
    exit 2
    ;;
esac

RUN_PREFIX="${RUN_PREFIX:-V17_P1R3}"
RUN_NAME="${RUN_PREFIX}_${CANDIDATE_ID}_chunk${CHUNK_ID}_h${HORIZON}_globalgate_H9parent_SWKS3"
RUN_DIR="$ROOT/$ROLLOUT_BASE/$RUN_NAME"

SAVE_MERGE_ENV=()
if [ "$SAVE_CANDIDATE_MERGE_STATES" = "1" ]; then
  SAVE_MERGE_ENV=(
    SAVE_MERGE_STATES="$MERGE_SAVE_BASE/$RUN_NAME"
    SAVE_MERGE_STATE_KINDS=input,after
  )
fi

if [ "${FORCE:-0}" != "1" ] && [ -f "$RUN_DIR/01.txt" ] && grep -q "DONE $RUN_NAME" "$RUN_DIR/run_status.txt" 2>/dev/null; then
  echo "SKIP existing DONE run: $RUN_NAME"
  exit 0
fi

env \
  KITTI_SEQ=01 \
  ATTN_CUE_BASE="$ROLLOUT_BASE" \
  START_FRAME="$START_FRAME" \
  END_FRAME="$END_FRAME" \
  GLOBAL_CHUNK_OFFSET="$CHUNK_ID" \
  RESET_EVERY=5 \
  WRITE_ALPHA=0.125 \
  READ_LAYER_MODE=all \
  READ_BETA_FRAME_CHUNKS="5:4.85,6:4.85,7:4.85,8:4.85,9:4.85,10:4.25,11:4.25,12:4.25,16:4.25" \
  ENABLE_SWA_OVERLAP_SOURCE_REPLACE=1 \
  SWA_OVERLAP_SOURCE_REPLACE_ALPHA=0.5 \
  SWA_OVERLAP_SOURCE_REPLACE_MODE=source \
  ENABLE_SWA_WRITE_CONTROL=1 \
  SWA_WRITE_LAYER_MODE=last \
  SWA_WRITE_KEEP_SCOPE=both_overlap \
  TTT_WRITE_GRADIENT_REVERSAL_MODE=tri_replay \
  TTT_WRITE_GRADIENT_REVERSAL_RISK_SOURCE=update_conflict_energy \
  TTT_WRITE_GRADIENT_REVERSAL_CHUNK_GAMMAS="$CHUNK_GAMMAS" \
  TTT_WRITE_NATIVE_MIX_SCALES="${TTT_WRITE_NATIVE_MIX_SCALES:-1.10,1.00,1.00}" \
  TTT_WRITE_TRI_REPLAY_POSITIVE_FRAC=0.35 \
  TTT_WRITE_TRI_REPLAY_NEGATIVE_FRAC=0.12 \
  TTT_WRITE_TRI_REPLAY_NEUTRAL_LAMBDA=0.85 \
  TTT_WRITE_TRI_REPLAY_CHUNK_PARAMS="$BASE_TRI_PARAMS" \
  LOAD_HMC_STATE_AT_CHUNK="$PHASE1/state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_HMC_STATE_AT_CHUNK_INDEX=0 \
  LOAD_MERGE_STATE_AT_CHUNK="$PHASE1/merge_state_snapshots/H9_P0_V16_R2/chunk_${SNAP}_input.pt" \
  LOAD_MERGE_STATE_AT_CHUNK_INDEX=0 \
  "${SAVE_MERGE_ENV[@]}" \
  "$ROOT/tools/run_attention_cue_experiment.sh" \
  "$GPU" "$RUN_NAME" hybrid acl2.gg.qq.low.g2_3.past_only.headmean.robustq 4.75 stage_d_x_dg_inv_sqrt
