#!/usr/bin/env python3
"""Compute v22 h10->h15 state overwrite diagnostics from saved HMC/merge states."""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

import torch

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def _iter_tensors(obj: Any, prefix: str = "root") -> Iterable[Tuple[str, torch.Tensor]]:
    if torch.is_tensor(obj):
        yield prefix, obj.detach().cpu()
        return
    if isinstance(obj, dict):
        for key, value in obj.items():
            yield from _iter_tensors(value, f"{prefix}.{key}")
        return
    if isinstance(obj, (list, tuple)):
        for idx, value in enumerate(obj):
            yield from _iter_tensors(value, f"{prefix}.{idx}")
        return
    if hasattr(obj, "__dict__"):
        for key, value in vars(obj).items():
            if key.startswith("_"):
                continue
            yield from _iter_tensors(value, f"{prefix}.{key}")


def _load(path: Path) -> Any:
    # These snapshots are generated by the local pipeline in this experiment and
    # contain HybridMemoryState objects, not just tensors. PyTorch 2.6 defaults
    # to weights_only=True, which rejects those trusted local state objects.
    return torch.load(path, map_location="cpu", weights_only=False)


def _tree_delta_norm(a: Any, b: Any, *, group: str | None = None) -> Tuple[float, int]:
    ta = dict(_iter_tensors(a))
    tb = dict(_iter_tensors(b))
    total = 0.0
    count = 0
    for key, va in ta.items():
        if group and f".{group}" not in key and not key.endswith(f".{group}"):
            continue
        vb = tb.get(key)
        if vb is None or tuple(va.shape) != tuple(vb.shape):
            continue
        diff = (vb.float() - va.float()).reshape(-1)
        total += float(torch.dot(diff, diff).item())
        count += 1
    return math.sqrt(total), count


def _state_summary(base: Any, h10: Any, h15: Any, label: str) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    groups = [None, "ttt", "swa", "ref", "frame", "global", "merge"]
    for group in groups:
        base_to_h10, n1 = _tree_delta_norm(base, h10, group=group)
        h10_to_h15, n2 = _tree_delta_norm(h10, h15, group=group)
        denom = base_to_h10 + 1e-8
        rows.append({
            "state_label": label,
            "tensor_group": "all" if group is None else group,
            "base_to_h10_norm": base_to_h10,
            "h10_to_h15_norm": h10_to_h15,
            "overwrite_ratio_h15_minus_h10_over_h10_minus_base": h10_to_h15 / denom,
            "base_to_h10_tensor_count": n1,
            "h10_to_h15_tensor_count": n2,
        })
    return rows


def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return rows


def _flatten_numeric(prefix: str, obj: Any, out: Dict[str, float]) -> None:
    if isinstance(obj, dict):
        for key, value in obj.items():
            _flatten_numeric(f"{prefix}.{key}" if prefix else str(key), value, out)
    elif isinstance(obj, (int, float)) and math.isfinite(float(obj)):
        out[prefix] = float(obj)


def _mean_debug_by_chunk(run_dir: Path) -> List[Dict[str, Any]]:
    rows = _read_jsonl(run_dir / "hmc_state_hash.jsonl")
    out: List[Dict[str, Any]] = []
    for row in rows:
        flat: Dict[str, float] = {}
        _flatten_numeric("", row, flat)
        out.append({
            "chunk_idx": int(row.get("chunk_idx", row.get("chunk", -1))),
            "memory_ttt_mean_rel_diff": flat.get("memory_side_effect.ttt_state_diff.mean_rel_diff", float("nan")),
            "memory_ttt_w0_mean_rel_diff": flat.get("memory_side_effect.ttt_state_diff.w0.mean_rel_diff", float("nan")),
            "memory_ttt_w1_mean_rel_diff": flat.get("memory_side_effect.ttt_state_diff.w1.mean_rel_diff", float("nan")),
            "memory_ttt_w2_mean_rel_diff": flat.get("memory_side_effect.ttt_state_diff.w2.mean_rel_diff", float("nan")),
            "mean_context_keep_ratio": flat.get("control_trace.hook_effect_summary.frame.mean_keep_ratio", float("nan")),
            "mean_swa_replace_alpha": flat.get("control_trace.hook_effect_summary.mean_swa_overlap_source_replace_alpha", float("nan")),
            "swa_write_tokens_before": flat.get("control_trace.hook_effect_summary.mean_swa_write_history_tokens_before", float("nan")),
            "swa_write_tokens_after": flat.get("control_trace.hook_effect_summary.mean_swa_write_history_tokens_after", float("nan")),
        })
    return out


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    fields: List[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--base-chunk", default="010")
    parser.add_argument("--h10-chunk", default="020")
    parser.add_argument("--h15-chunk", default="025")
    args = parser.parse_args()

    hmc_dir = args.run_dir / "hmc_state_snapshots"
    if not hmc_dir.exists():
        hmc_dir = args.run_dir / "state_snapshots"
    merge_dir = args.run_dir / "merge_state_snapshots"

    hmc_base = hmc_dir / f"chunk_{args.base_chunk}_input.pt"
    hmc_h10 = hmc_dir / f"chunk_{args.h10_chunk}_after.pt"
    hmc_h15 = hmc_dir / f"chunk_{args.h15_chunk}_after.pt"
    required = [hmc_base, hmc_h10, hmc_h15]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing required HMC state files: " + ", ".join(missing))

    rows = _state_summary(_load(hmc_base), _load(hmc_h10), _load(hmc_h15), "hmc")

    merge_base = merge_dir / f"chunk_{args.base_chunk}_input.pt"
    merge_h10 = merge_dir / f"chunk_{args.h10_chunk}_after.pt"
    merge_h15 = merge_dir / f"chunk_{args.h15_chunk}_after.pt"
    if merge_base.exists() and merge_h10.exists() and merge_h15.exists():
        rows.extend(_state_summary(_load(merge_base), _load(merge_h10), _load(merge_h15), "merge"))

    args.out_dir.mkdir(parents=True, exist_ok=True)
    _write_csv(args.out_dir / "state_overwrite_summary.csv", rows)
    (args.out_dir / "state_overwrite_summary.json").write_text(
        json.dumps(rows, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    debug_rows = _mean_debug_by_chunk(args.run_dir)
    _write_csv(args.out_dir / "chunk_debug_summary.csv", debug_rows)
    (args.out_dir / "chunk_debug_summary.json").write_text(
        json.dumps(debug_rows, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    md = ["# v22 State Attribution", ""]
    md.append(f"Run: `{args.run_dir.name}`")
    md.append("")
    md.append("State overwrite ratio is `||state_h15 - state_h10|| / (||state_h10 - state_base|| + eps)`.")
    md.append("")
    md.append("| State | Group | base->h10 | h10->h15 | ratio | tensors |")
    md.append("|---|---|---:|---:|---:|---:|")
    for row in rows:
        md.append(
            f"| `{row['state_label']}` | `{row['tensor_group']}` | "
            f"{float(row['base_to_h10_norm']):.6g} | "
            f"{float(row['h10_to_h15_norm']):.6g} | "
            f"{float(row['overwrite_ratio_h15_minus_h10_over_h10_minus_base']):.6g} | "
            f"{int(row['h10_to_h15_tensor_count'])} |"
        )
    (args.out_dir / "state_overwrite_summary.md").write_text("\n".join(md) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
